### DISCUSSION TITLE
Port mapping works for IPv6 but not IPv4

### DISCUSSION THREAD

**Discussion by flo1o1** [caprover/caprover#1739] [Q&A]
Hi all,

I’m running a Minecraft server instance as 1 click app. 

The port mapping works for my public IPv6 but not for my public IPv4 address. This makes Minecraft clients think the server is unreachable.

When running `lsof -i`, I see the Minecraft server port being opened on IPv6, but not n IPv4. I was expecting ports to be mapped to both IPv6 and IPv4.

I’m not a Docker guru, so maybe someone can point me to right place to look at or give me a hint? Is this a CapRover or Docker configuration thing?

- RAM: 7.76 GB
- OS: Ubuntu Linux
- CPU: 4 cores
- Architecture: x86_64
- Docker Version: 23.0.5

Any help highly appreciated!

Florian

**Comment by githubsaturn** [comment]
This is not CapRover, it's Docker. CapRover simply passes down the ports to Docker.

And Docker automatically binds all network interfaces unless you have a specific Docker/netowrk configuration on your machine.

What do you see when you run `lsof -i | grep 3000` ?

**Comment by flo1o1** [comment]
Hi @githubsaturn,

thanks for your quick reply. This is what lsof prints:

```
# lsof -i | grep 3000
docker-pr  1416            root    4u  IPv4  23242      0t0  TCP *:3000 (LISTEN)
```

**Reply by githubsaturn** [reply]
So it looks like port 3000 which is being used by `captain-captain` is correctly set up to IPv4.

You can try using service override to use `host` mode for your app to see if it helps:
```yaml
EndpointSpec:
  Mode: vip
  Ports:
    - Name: something
      Protocol: tcp
      TargetPort: <container port>
      PublishedPort: <exposed port on host>
      PublishMode: host
```
