### DISCUSSION TITLE
Mounting network folders via Rclone in containers

### DISCUSSION THREAD

**Discussion by adamshand** [caprover/caprover#1956] [Q&A]
Hello,

I've been playing around with creating Docker volumes with the docker-rclone plugin.  This docker-compose file seems to be working as expected (nothing special about memos, I'm just using it as a simple container to test with):

```
❯ cat /tmp/docker-compose.yml
version: "3.8"

volumes:
  memosrclone:
    driver: rclone
    driver_opts:
      remote: b2:caprover-app/memos
      vfs-cache-mode: full

services:
  memos:
    image: neosmemo/memos:latest
    volumes:
      - memosrclone:/var/opt/memos
    ports:
      - 5230:5230
    environment:
      - MEMOS_METRIC=false

❯ docker stack deploy memos -c /tmp/docker-compose.yml
Creating service memos_memos

❯ docker service ls
ID             NAME                       MODE         REPLICAS   IMAGE                              PORTS
4irkrcm0frdj   captain-captain            replicated   1/1        caprover/caprover:1.11.1
rt0a2jgcn3nq   captain-certbot            replicated   1/1        caprover/certbot-sleeping:v1.6.0
4ut3a505o38r   captain-nginx              replicated   1/1        nginx:1.24
e2i2k63xobqm   memos_memos                replicated   0/1        neosmemo/memos:latest              *:5230->5230/tcp
```

I can rm the service and recreate it and the data perisists.

However, I'm I'm not sure how to make this work with CapRover.    I've tried adapting it to a template (as per the CapRover [docker compose docs](https://caprover.com/docs/docker-compose.html)) like this:

```
captainVersion: 4
caproverOneClickApp:
    instructions:
        start: |-
            An open-source, self-hosted memo hub with knowledge management and socialization.

            See https://usememos.com for more details.
        end: |-
            Memos has been deployed!
    displayName: memos
    isOfficial: false
    description: An open-source, self-hosted memo hub with knowledge management and socialization.
    documentation: https://usememos.com
########
version: "3.8"

volumes:
  memos-rclone:
    driver: rclone
    driver_opts:
      remote: b2:caprover-app/memos
      vfs-cache-mode: full

services:
  memos:
    image: neosmemo/memos:latest
    volumes:
      - memos-rclone:/var/opt/memos
    ports:
      - 5230:5230
    environment:
      MEMOS_METRIC: 'false'
```

This creates a usable memos app, but the memos-rclone volume is empty (no persisted data from B2). 

I see in [the "stateless with persistent data" docs](https://caprover.com/docs/stateless-with-persistent-data.html) that they are creating the volumes outside of CapRover.  I was hoping to avoid doing this because I'd like to manage quite a few applications this way and manaually keeping all of the volumes in sync across all the nodes in a swarm seems like it's an accident waiting to happen.

Is there a way to have CapRover create an Rclone volume as part of the container/service creation?

Thanks for any pointers.
Adam.

**Comment by githubsaturn** [comment]
Unfortunately, your findings are correct! You can't use one click app templates. The one click app template is a "forged" docker compose... Unfortunately, Docker doesn't expose Docker Compose functionality as an API. Docker Compose is just a CLI tool that talks to Docker API. CapRover only talks to Docker API, so we tried to mimic super basic functionalities of Docker Compose, of course, this means that there are many many features that work in Docker Compose but won't work in CapRover.

Most of these shortcomings can be addressed via [Service Override](https://caprover.com/docs/service-update-override.html). From my brief research it looks like the volume driver is supported in [service update](https://docs.docker.com/engine/api/v1.40/#tag/Service/operation/ServiceUpdate).

Maybe something like this works (totally untested, so probably doesn't work as is, but a good starting point)

```yaml
TaskTemplate:
  ContainerSpec:
    Mounts:
      - Type: volume
        Source: memos-rclone
        Target: /var/opt/memos
        VolumeOptions: 
          DriverConfig:
            name: rclone
            Options:
              remote: b2:caprover-app/memos
              vfs-cache-mode: full
```

![image](https://github.com/caprover/caprover/assets/10582082/cd96d037-cd03-440a-b599-3eae35da25c3)
