### DISCUSSION TITLE
Workflow for deploying from github a docker-compose with folders

### DISCUSSION THREAD

**Discussion by dreaded369** [caprover/caprover#1957] [Q&A]
I've got a few docker compose projects that include local folders (and they use ./folder in the volumes parameter).

Currently I'm assuming the workflow to use these would be to:
1. Create new app
2. Add persistent storage
3. Copy files to newly created storage folder (outside caprover)
4. Create caprover flavoured docker-compose file with new storage location.

Is there an alternative? 
Would this be a job for a pre-deploy script?

A more advanced variant would be pulling a repository that has local files/folders and a docker-compose file which includes a build command.

**Comment by dreaded369** [comment]
Actually that workflow is wrong, and using the one-click-app template for docker compose you don't get a chance to add persistent storage before deploy.

**Reply by githubsaturn** [reply]
There are two methods you can use:

1- Use one click app and deploy normally using named volumes

Then, create a symlink between your actual directory on disk and map it to the location of named volume (use `docker volume inspect....` to get the mounting point)



Or
2- First create your directories on the host and then deploy the one click app template, example
```
captainVersion: 4
services:
    $$cap_appname:
        image: someimage:latest
        environment:
            ENV1:Value1
        volumes:
            - /my/host/directory:/my/container/directory
```
