### DISCUSSION TITLE
Updating one-click-apps when template build docker container?

### DISCUSSION THREAD

**Discussion by adamshand** [caprover/caprover#1963] [Q&A] [answered]
Hello,

Still wrapping my head around how CapRover does updates in some instances.  In the below template file, the Pocketbase container is built using a Dockerfile.

If you used this template to install Pocketbase, how would you update it to a newer version later?  There's no Docker Hub image to reference?

I assume you'd use method 4 or 5 and adapt the template to an actual Dockerfile or captain-definition?

Which is easy enough but seems annoying to do for every update?

Am I missing something or is the better solution (in this specific case) to update the template to use a prebuilt image?

Thanks!
Adam.

```
services:
    '$$cap_appname':
        caproverExtra:
            dockerfileLines:
                - FROM alpine:3.16.2
                - RUN apk add --no-cache unzip openssh
                - ADD https://github.com/pocketbase/pocketbase/releases/download/v$$cap_version/pocketbase_$$cap_version_$$cap_architecture.zip /tmp/pb.zip
                - RUN unzip /tmp/pb.zip -d /pb/
                - EXPOSE 8080
                - CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
            containerHttpPort: '8080'
        volumes:
            - '$$cap_appname-data:/pb'
```
