### DISCUSSION TITLE
How to prevent all replicas from being deleted when only one fails?

### DISCUSSION THREAD

**Discussion by erickythierry** [caprover/caprover#2164] [Q&A]
Greetings.
I believe this issue is more related to Docker Swarm.
However, since I am using Caprover, I believe I can get some idea of ​​a solution here.

I have a project running on Caprover, and the idea is to use container replication to increase and decrease the demand for instances.

However, I have been doing some tests and I noticed that, if a single replica shuts down for any reason, the Swarm ends up shutting down all the others and recreates them all again, and this affects the functioning of my system.
Is there any way to avoid this? Instruct Docker to only recreate the instance with the problem and keep the others intact?

I tried using some settings in Service Update Override
```
UpdateConfig:
  Parallelism: 1
  Delay: 1000000000
  FailureAction: continue
  Monitor: 10000000000
  MaxFailureRatio: 0.50
  Order: start-first
RollbackConfig:
  Parallelism: 1
  Delay: 1000000000
  FailureAction: continue
  Monitor: 10000000000
  MaxFailureRatio: 0.50
  Order: stop-first
```
but without success.
if an instance is terminated, all the others follow suit and then come up together.

I've been using swarm for a few weeks now and I thought it would be more versatile, but this type of behavior is really frustrating.

**I appreciate anyone who can help me with any tips.**
