### DISCUSSION TITLE
Support for volume file mounts in one-click-apps

### DISCUSSION THREAD

**Discussion by nktnet1** [caprover/caprover#2245] [Ideas]
Hello,

I believe currently, there is no way to create a one-click-app template that comes with a persistent config file mounted in volume, e.g. a python file such as `superset_config.py`.

For context, I would like to convert the following [superset template](https://github.com/amancevice/docker-superset/blob/9c648b93705356e41ba428fb68b2235e46b4ed6c/examples/postgres/compose.yml):
```yaml
services:
  db: .....
  redis: .....
  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - db
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      # Ideally create this file automatically with one-click-apps
      - ./superset_config.py:/etc/superset/superset_config.py
```

In alternatives like Dokploy/Coolify, this is possible using
- [Dokploy's mounts in index.ts](https://github.com/Dokploy/dokploy/blob/c6569f70e469146a98946d8f9ad2e5619527c3c7/apps/dokploy/templates/superset/index.ts#L34-L58)
- [Coolify's volume content](https://github.com/coollabsio/coolify/pull/4891/files#diff-fcc050c0f4ad03ac0c678aeb98ea8dff0fbe1cd03c4337af1cdeafc2065f16d5R16-R42)  -  see [docs](https://coolify.io/docs/knowledge-base/docker/compose/#create-a-file-with-content)

Would it be possible to implement something similar for Caprover?
