### DISCUSSION TITLE
How to deploy an app using another app's image via CLI?

### DISCUSSION THREAD

**Discussion by erickythierry** [caprover/caprover#2280] [Q&A]
I was looking for discussion threads here, and I found this one about deploying via CLI by passing the `--imageName` parameter to define the image name.
[1434](https://github.com/caprover/caprover/discussions/1434)

This would be close to what I need to do.

I currently have some servers running with caprover and docker swarm. I have 2 apps that are basically the same base, but I deploy them individually using caprover CLI via github actions, and it turns out that the image build occurs in both deploys.
My idea would be to deploy the first one, and then the second one would just get this image from the first one.
How could I do this via CLI?

I imagine that I have to get the name of the last image created in the build of the first app to pass to the --imageName parameter, is there any way I can get this value dynamically?
![image](https://github.com/user-attachments/assets/5a119498-034b-4532-8b38-5e90d6b6df4f)
an example of how my github actions is. I deploy these 2 apps in sequence, but the deployment takes a certain amount of time, so I wanted to reduce this time by half by reusing the image from the first deploy

**Comment by githubsaturn** [comment]
You would need to build on CI/CD and have your image be deployed to a 3rd party registry like Github. Then have the action to deploy the same image to two apps. 

See here: https://caprover.com/docs/ci-cd-integration/deploy-from-github.html#create-the-github-action


Basically you need to duplicate this block which sits at the bottom of the config:

```yml

    - name: Deploy Image to CapRrover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ secrets.APP_NAME }}"
        token: "${{ secrets.APP_TOKEN }}"
        image: ${{ env.IMAGE_URL }}
```
