### DISCUSSION TITLE
Docker compose "command" property may not work correctly

### DISCUSSION THREAD

**Discussion by s-h-a-d-o-w** [caprover/caprover#2285] [Q&A]
Running the following template:

```yml
captainVersion: 4
services:
    $$cap_appname:
        image: gcr.io/cadvisor/cadvisor:$$cap_version
        restart: always
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        command:
            - '-housekeeping_interval=10s'
            - '-docker_only=true'
        ports:
            - 8080:8080
caproverOneClickApp:
    variables:
        - label: cAdvisor version number
          defaultValue: v0.52.1
          description: 'Release versions can be used: https://github.com/google/cadvisor/releases/tag/v0.52.1'
          id: $$cap_version
    instructions:
        end: 'You can now scrape the data at port 8080.'
        start: 'Read about it here: https://github.com/google/cadvisor'
    displayName: cAdvisor
    isOfficial: false
    description: Analyzes resource usage and performance characteristics of running containers.
    documentation: https://github.com/google/cadvisor
```

Results in: `starting container failed: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"-housekeeping_interval=10s\": executable file not found in $PATH: unknown` (from `journalctl`. Docker logs are empty.)

Running it _without_ `command` values works and I can run it _with_ those values directly with docker-compose.

**Comment by s-h-a-d-o-w** [comment]
Figured it out, I think. It's because even though those configs look like docker compose files, they aren't and unlike with docker compose, "command" will overwrite the entry point declaration. This works: 

```yml
captainVersion: 4
services:
    $$cap_appname:
        image: gcr.io/cadvisor/cadvisor:$$cap_version
        restart: always
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        command:
            - '/usr/bin/cadvisor'
            - '-logtostderr'
            - '-housekeeping_interval=10s'
            - '-docker_only=true'
        ports:
            - 8080:8080
caproverOneClickApp:
    variables:
        - label: cAdvisor version number
          defaultValue: v0.52.1
          description: 'Release versions can be used: https://github.com/google/cadvisor/releases/tag/v0.52.1'
          id: $$cap_version
    instructions:
        end: 'You can now scrape the data at port 8080.'
        start: 'Read about it here: https://github.com/google/cadvisor'
    displayName: cAdvisor
    isOfficial: false
    description: Analyzes resource usage and performance characteristics of running containers.
    documentation: https://github.com/google/cadvisor
```

I would recommend adding a sentence about this to the template one click app. Ideally linking to docker docs, if there are any for this. By which I don't just mean this behavior but the overall behavior, so that people know what they can use in one click app definitions and how it'll behave. I looked a bit through the docker swarm docs but couldn't find anything—but I only skimmed for a minute or two.
