### ISSUE TITLE
Multiline strings for description under variables

### ISSUE THREAD

**Issue by kgnfth** [caprover/caprover#1151]
### Is your feature request related to a problem? Please describe.
When we create an one click app in yaml, sometimes under description we need to add a newline to make it more readable

but the block scalars does not work for description under the variables section

### **Describe the solution you'd like**
Support block scalars for description under variables like this
```yaml
caproverOneClickApp:
    variables:
        - id: $$cap_default_access
          label: Default access type
          description: |-
              Choose between FULL_ACCESS or VIEW_ACCESS,
              FULL_ACCESS = No password needed, everyone can delete, add sources
              VIEW_ACCESS = password required to add, delete sources
              VIEW_ACCESS is reccomended
```

### **Additional context**
_Before_
![image](https://user-images.githubusercontent.com/73314940/126558280-a6c32e3f-9293-4be3-a2c1-bb77e6f518af.png)
_After_
![image](https://user-images.githubusercontent.com/73314940/126558535-ba6b0477-f5b2-4b51-b1af-d81d5d645155.png)
