### ISSUE TITLE
[Deployment Issue] docker hub rate limit, still not solved

### ISSUE THREAD

**Issue by doebi** [caprover/caprover#1189]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?

Running into rate limit error although authenticated and pulling works on cli.

![Screenshot from 2021-09-07 20-07-09](https://user-images.githubusercontent.com/1591457/132391165-65caaf9a-cc79-4b23-8686-e93db37063a0.png)

If applicable, content of `captain-definition` file:
![Screenshot from 2021-09-07 20-07-25](https://user-images.githubusercontent.com/1591457/132391207-e64739fc-415f-4bad-8cee-5bd30b381679.png)
![Screenshot from 2021-09-07 20-08-44](https://user-images.githubusercontent.com/1591457/132391218-2e8476f1-b845-47ab-8ec0-11d1b7b3e12c.png)
![Screenshot from 2021-09-07 20-07-47](https://user-images.githubusercontent.com/1591457/132391233-1ccb088b-fe23-4e37-8186-d1b686f2ec56.png)

Steps to reproduce the problem:
Use on-click installer to install an app. in this case: matomo.

Answers to the following questions if applicable:
- Your OS and version?
- RAM?

**Comment by githubsaturn** [comment]
For your docker hub URL use
```
registry-1.docker.io
```

**Comment by doebi** [comment]
Same. I had that earlier and did trial and error with several different settings for the last couple of hours. The result stays the same.

**Comment by doebi** [comment]
@githubsaturn Thanks for your effort. I did as you described, with the same (or very similar) outcome. UI reports yet another error 500, the app log says that URL returns a 404.

I feel like this is more of a bug in the "registry configuration" now and not simply a deployment issue. 

![Screenshot from 2021-09-08 06-51-09](https://user-images.githubusercontent.com/1591457/132448502-5e9fdb73-3e49-48ca-ba00-fcd92cb1997e.png)

**Comment by githubsaturn** [comment]
:man_facepalming: 
Looks like Docker has changed the domain for Docker Hub to `docker.io`. Try this:
- Go to CLUSTER tab and add a remote registry:
Username: your docker username (NOT EMAIL)
URL: `docker.io`
Password: your docker password
ImagePrefix: your docker username

Now try this template:
```
captainVersion: 4
services:
    $$cap_appname-db:
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_DATABASE: matomo
            MYSQL_USER: matomo
            MYSQL_PASSWORD: $$cap_db_pass
            MYSQL_RANDOM_ROOT_PASSWORD: true
        caproverExtra:
            dockerfileLines:
                - FROM mariadb:$$cap_mysql_version
                - CMD ["--max-allowed-packet=64MB"]
            notExposeAsWebApp: 'true'
    $$cap_appname:
        depends_on:
            - $$cap_appname-db
        image: docker.io/matomo:$$cap_matomo_version
        restart: always
        volumes:
            - $$cap_appname-data:/var/www/html
        documentation: taken from https://github.com/matomo-org/docker/blob/master/.examples/apache/docker-compose.yml example
        environment:
            MATOMO_DATABASE_HOST: srv-captain--$$cap_appname-db
            MATOMO_DATABASE_ADAPTER: mysql
            MATOMO_DATABASE_TABLES_PREFIX: matomo_
            MATOMO_DATABASE_USERNAME: matomo
            MATOMO_DATABASE_PASSWORD: $$cap_db_pass
            MATOMO_DATABASE_DBNAME: matomo
caproverOneClickApp:
    variables:
        - id: $$cap_matomo_version
          label: Matomo Version
          defaultValue: 4.2.1
          description: Check out their docker page for the valid tags https://hub.docker.com/_/matomo?tab=tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_mysql_version
          label: MariaDB Version
          defaultValue: 10.5.9
          description: Check out their docker page for the valid tags https://hub.docker.com/_/mariadb?tab=tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_db_pass
          label: MariaDB Root Password
          description: The root password to use for the MariaDB instance
          validRegex: /.{1,}/
          defaultValue: $$cap_gen_random_hex(32)
    instructions:
        start: Matomo is the leading open-source analytics platform that gives you more than powerful analytics.
        end: >-
            Matomo is successfully deployed!
            your application will be available in the next few seconds. Please note to enable https if you need to track datas on https websites.
    displayName: ''
    isOfficial: true
    description: Matomo tracks online visits to one or more websites and displays reports on these visits for analysis
    documentation: Taken from https://hub.docker.com/_/matomo?tab=description
```
