### ISSUE TITLE
Impossible to use `{test:"{.Text}"}` in app template

### ISSUE THREAD

**Issue by paskal** [caprover/caprover#1328]
Hello there!

## Bug setup

App template:
```yaml
captainVersion: 4
services:
    $$cap_appname:
        image: non-existent:latest
        environment: {}
caproverOneClickApp:
    variables:
        - id: $$cap_test_var
          label: 'test'
          defaultValue: '{test:"{.Text}"}'
    instructions:
        start: ""
        end: ""
    displayName: test app
    isOfficial: true
    description: test app
```

I insert the template above into `One Click Apps` -> `>> TEMPLATE <<`, on the next window set `App Name` to `test` and click `Deploy`.

## Expected result

The application that tried to be deployed likely dies due to the wrong image name.

## Actual result

Error "Parsing the template":

```
Cannot parse: {"captainVersion":4,"services":{"test":{"image":"non-existent:latest","restart":"always","environment":{},"caproverExtra":{"containerHttpPort":"8080"}}},"caproverOneClickApp":{"variables":[{"id":"test","label":"App Name","description":"This is your app name. Pick a name such as my-first-1-click-app","validRegex":"/^([a-z0-9]+\\-)*[a-z0-9]+$/"},{"id":"{test:"{.Text}"}","label":"test","defaultValue":"{test:\"{.Text}\"}"},{"id":"capover.ksinia.com","label":"CapRover root domain"}],"instructions":{"start":"","end":""},"displayName":"test app","isOfficial":true,"description":"test app"}} SyntaxError: JSON Parse error: Expected '}'
```

## Notes

It seems like variable value is embedded into JSON without escaping curvy braces, which leads to the error above.
