### ISSUE TITLE
$$cap_appname is not available in the variable defaultValue

### ISSUE THREAD

**Issue by paskal** [caprover/caprover#1329]
## Setup

Create a new app using the template below:

```yaml
captainVersion: 4
services:
    $$cap_appname:
        image: alpine:latest
        environment:
            TEST: $$cap_test_var
caproverOneClickApp:
    variables:
        - id: $$cap_test_var
          label: 'test'
          defaultValue: '$$cap_appname.$$cap_root_domain'
    instructions:
        start: ""
        end: ""
    displayName: test app
    isOfficial: true
    description: test app
```

## Expected result

Environment variable TEST expanded to `$$cap_appname.$$cap_root_domain` values

## Actual result

`$$cap_root_domain` is expanded, but `$$cap_appname` is not.
