### ISSUE TITLE
Feature for nginx location aliased to a persistent volume

### ISSUE THREAD

**Issue by johncronan** [caprover/caprover#1343]
**Is your feature request related to a problem? Please describe.**
I've adapted the docker-compose.yml file that I wrote for [Formative](https://github.com/johncronan/formative), in the hopes of making this a CapRover one-click app. This is a form builder app that handles media files similar to a CMS - user uploads might include large video files.

And it works! I came up with something that looks like this:

```
captainVersion: 4
services:
    $$cap_appname-db:
        image: postgres:13
        [...]
    $$cap_appname-mta:
        image: juanluisbaptiste/postfix:1.3
        [...]
    $$cap_appname:
        image: formative/formative:latest
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-mta
        environment:
            [lots of environment variables ...]
        caproverExtra:
            containerHttpPort: ‘8000’
        volumes:
            - $$cap_appname-plugins:/opt/services/djangoapp/requirements
            - /captain/data/nginx-shared/formative_media:/opt/services/djangoapp/media
caproverOneClickApp:
    variables:
        - id: $$cap_formative_admin
          label: Admin username
          defaultValue: admin
          description:
          validRegex: /^([a-zA-Z0-9_@\.-])+$/
        - id: $$cap_formative_email
          label: Admin email
          description:
          validRegex: /^([a-zA-Z0-9_@\.-])+$/
        - id: $$cap_formative_password
          label: Admin password
          description:
          validRegex: /.{1,}/
        - id: $$cap_db_username
          label: Database username
          description:
          validRegex: /^([a-zA-Z0-9_])+$/
        - id: $$cap_db_password
          label: Database password
          description:
          validRegex: /.{1,}/
        - id: $$cap_db_database
          label: Database name
          defaultValue: formative
          description:
          validRegex: /^([a-zA-Z0-9_])+$/
          [some more ...]
    displayName: Formative
    isOfficial: false
    description: Self-hosted web app for collecting form responses and files. For application forms, you can use it together with reviewpanel to review and score applicant submissions.
```

The thing is, I've had to resort to creating a new directory under nginx-shared for the media volume. Eventually, I want to have access control enforced by my Django application, using X-Accel-Redirect to serve the files from nginx. Routing all that data transfer through gunicorn would compromise the performance pretty significantly.

Therefore, following the deployment we still need to add a `location /media/ { alias /nginx-shared/formative_media/; }` block to the nginx config.

I've also noted the following 2 problems:

- my containerHttpPort directive isn't working - I have to go to the app after it deploys and set the port to 8000. should I open a separate issue for this, or is it something simple that I've missed?
- since 'command' is not among the supported docker-compose fields, there is no way for me to use the official postgres image and apply configuration changes (even after moving them from command line arguments to a config file, still it is necessary to add `-c configfilelocation.conf` to the arguments). so same question - should I perhaps open a separate issue?

**Describe the solution you'd like**
With regard to the media volume issue, in my regular docker-compose.yml file, I create a docker volume that is mounted to both containers, nginx and the app.

Here's the solution that I would most prefer: a new field in caproverExtra that allows specifying a mapping between one of the service's volumes and an alias location that gets added to the nginx config. That would require adding to the nginx container's volumes, leaving nginx-shared out of it.

However, my goal is simply this: remain self-hosted, and achieve one-click deployment. I'd like to find out what you all think.

**Describe alternatives you've considered**
The only alternative that comes to mind, given that I want to remain fully self-hosted, is to require something else in addition to CapRover as a dependency for installation. That is, to run an additional server at the host level that handles serving the media. I could make my app one click to deploy, but then it would need to prompt the admin to configure this additional capability. I haven't thought deeply about what that would mean. It seems not ideal.

Thanks very much for CapRover!
