### ISSUE TITLE
Shared SSH Keys

### ISSUE THREAD

**Issue by Tam2** [caprover/caprover#1353]
**Is your feature request related to a problem? Please describe.**
We deploy via github webhooks using SSH Keys, this works great, but we have the copy the SSH key to each app

**Describe the solution you'd like**
Would be good if there was a way to store SSH keys within the application and then have the option to use an existing (stored) SSH Key or enter like you currently can

**Describe alternatives you've considered**
None, continue with current option of entering SSH Key for each app

**Additional context**

**Comment by maietta** [comment]
We switched from SSH keys to App Tokens and adopted the following workflow template for most of our website projects:

The CAPROVER_SERVER secret is added to out Github organization secrets and then using APP_TOKEN and APP_NAME for our project specific secrets. It's much easier and it also means the flow only bundles up our deployment files to deploy, rather than the entire Github project being sent. The caprover secret is defined with https://captain.prod-apps.your-domain.com.

I'm only offering this if this makes it easier for your scenario.

```
name: Deploy to Production (main branch)
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Package up a deployment tarball
      - uses: actions/checkout@master
      - name: Compress action step
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./public_app_files
            ./captain-definition
            ./Dockerfile
          outPath: deploy.tar

      - name: Push to Caprover
        uses: premoweb/deploy-to-caprover@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          branch: 'main'
```
