### ISSUE TITLE
Connecting caprover/nginx-reverse-proxy to a local docker-compose service

### ISSUE THREAD

**Issue by dabeeeenster** [caprover/caprover#1371]
I wanted to run [pihole](https://pi-hole.net/) in Caprover but am unable to due to a requirement for `cap_add: - NET_ADMIN` which I understand caprover cannot support. 

So I ran it as a local self-contained docker image using this compose file:

```
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9081:80/tcp"
    environment:
       TZ: 'Europe/London'
       WEBPASSWORD: 'XXXX'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

This exposes a web interface on port 9081. I then wanted to use `caprover/nginx-reverse-proxy` to put TLS in front of this service but I cant figure out how to reference the proxy - is this even possible? I'm thinking I need to set up some networking between the caprover docker swarm and the docker-compose but I'm not sure how to do that? 

Thanks!
