### ISSUE TITLE
[Deployment Issue] Deployment of Mealie as a persistent app

### ISSUE THREAD

**Issue by 9j7axvsLuF** [caprover/caprover#1405]
I'm new to Caprover and self-hosting in general, but I've had no issues using one-click apps. 

I'm now trying to deploy [Mealie](https://hay-kot.github.io/mealie/documentation/getting-started/install/), which is not available as a one-click app. I successfully deployed it using the latest Docker image (hkotel/mealie:latest), and it works, however I can't figure out how to make the database persistent. I've trying reading both Caprover and Mealie documentation, but I'm really lost. Any help would be much appreciated!

**Comment by githubsaturn** [comment]
First, when you create the app, make sure you check the persistent box.
Then after you deployed your app, you can go to Apps > your app > App config and add the correct path. 

Probably what's going to be easier is this though:
- Go to one click apps
- Select `>> Template <<`
- 
![image](https://user-images.githubusercontent.com/10582082/166162407-c7a6ff75-e7a7-456a-9005-13a16a43f76d.png)
- Then for the content, just paste this:
```yaml
captainVersion: 4
caproverOneClickApp:
    instructions:
        start: Just a plain Docker Compose.
        end: Docker Compose is deployed.
########
version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9925:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Anchorage

      # Default Recipe Settings
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'

      # Gunicorn
      # WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - db_data:/app/data
      # Check this line above <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```
