### ISSUE TITLE
Underscore not allowed in volume name

### ISSUE THREAD

**Issue by MrSnoozles** [caprover/caprover#1446]
## What is the problem?
To deploy [Jitsu](https://jitsu.com/docs/deployment/deploy-with-docker/joint-image), it is required to create a volume named `jitsu_workspace`. That unfortunately is not possible, because Caprover does not allow underscores in volume names. **Would it be possible to set the name to `jitsu_workspace` somehow?**  (also excluding the `captain--` prefix)

## Steps to reproduce the problem:

Try to add a persistent directory with the label `jitsu_workspace`
![grafik](https://user-images.githubusercontent.com/17496592/173900372-3bc42fd0-4f57-4241-9577-3fe3c00de072.png)

**Comment by githubsaturn** [comment]
CapRover name spaces everything to avoid potential clashes with other Docker services running on the host. 

It is possible to bypass this by using [Service Override](https://caprover.com/docs/service-update-override.html)

Have something like this in your service override section:
```
TaskTemplate:
  ContainerSpec:
    Mounts:
      - Type: volume
        Source: jitsu_workspace
        Target: /some/path/in/container
        ReadOnly: false
      - Type: volume
        Source: another_volume
        Target: /some/path/in/container/another/path
        ReadOnly: false
```
