### ISSUE TITLE
[Question] Use custom subdomain in app definition file

### ISSUE THREAD

**Issue by eikaramba** [caprover/caprover#1452]
I would like to directly specify a custom subdomain when i use a one-click template.

Here is my example template i use to fire up a directus instance:
```
captainVersion: 4
services:
    $$cap_appname-backend:
        image: directus/directus:latest
        volumes:
            - $$cap_appname-uploads:/directus/uploads
            - $$cap_appname-database:/directus/database
            - $$cap_appname-extensions:/directus/extensions
        restart: always
        hostname: api.$$cap_appname.$$cap_root_domain #<-- This seems to not working
        environment:
            KEY: $$cap_directus_auth_public_key
            SECRET: $$cap_directus_auth_secret_key
            ADMIN_EMAIL: $$cap_admin_email
            ADMIN_PASSWORD: $$cap_admin_password
            PUBLIC_URL: https://api.$$cap_appname.captain.localhost
            ACCESS_TOKEN_TTL: 60m
            CORS_ENABLED: true
            CORS_ORIGIN: array:http://localhost:3000,http://localhost:8055,https://$$cap_appname.captain.localhost/
        caproverExtra:
            containerHttpPort: '8055'
            # forceSsl: true
            customDomain:
              publicDomain: api.$$cap_appname.$$cap_root_domain #<-- This seems to not working
              hasSsl: false

caproverOneClickApp:
    variables:
        - description: Directus Auth Secret Key (must not be the same as Directus Auth Public Key)
          defaultValue: $$cap_gen_random_hex(16)
          id: $$cap_directus_auth_secret_key
          label: Directus Auth Secret Key
          validRegex: /^(?=.*\d).{10,}$/
        - description: Directus Auth Public Key (must not be the same as Directus Auth Secret Key)
          defaultValue: $$cap_gen_random_hex(16)
          id: $$cap_directus_auth_public_key
          label: Directus Auth Public Key
          validRegex: /^(?=.*\d).{10,}$/
        - description: Directus admin user email
          defaultValue: admin@test.de
          id: $$cap_admin_email
          label: Directus admin user email
          validRegex: /.{1,}/
        - description: Directus admin user password
          defaultValue: Test12345
          id: $$cap_admin_password
          label: Directus admin user password
          validRegex: /^(?=.*\d).{8,}$/
    instructions:
        end: >
            Aaaand you're done!
            Your service is available at http://$$cap_appname-backend.$$cap_root_domain
        start: >-
            Directus is an open-source suite of software that wraps custom SQL databases with a dynamic API and intuitive Admin App.
            For more information and available options, see https://github.com/directus/docker or the official documentation at https://docs.directus.io
    displayName: 'Directus'
    isOfficial: true
    description: Directus is an open-source tool for managing content across all your omni-channel digital experiences
    documentation: Taken from https://docs.directus.io/guides/installation/docker/.
```

You can see that i am trying to specify a custom subdomain `api.$$cap_appname.$$cap_root_domain` which is not working. CapRover is always just creating the default domain `$$cap_appname.$$cap_root_domain`

From a quick glance at the [sourcecode ](https://github.com/caprover/caprover/blob/master/src/datastore/AppsDataStore.ts#L55) i thought it should work (i also tried to set forceSsl to true.
