### ISSUE TITLE
[Question] Github Actions sends deploy.tar which doesn't work, but the same file manually deployed works.

### ISSUE THREAD

**Issue by maietta** [caprover/caprover#1453]
Pretty versed in deploying apps in Caprover, but this one has me ultra-stumped.

I have a Github Action as follows:

```
name: Build & Deploy Full Stack App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build-production --if-present
      - run: npm run test --if-present

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            dist/
            backend/
            captain-definition
          outPath: deploy.tar

      - uses: actions/upload-artifact@v3
        with:
          name: inspect
          path: deploy.tar

      - uses: premoweb/deploy-to-caprover@main
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          branch: '${{ github.ref }}'
```

My captain-definition looks like this:

```
{
    "schemaVersion": 2,
    "dockerfileLines": [
                          "FROM ghcr.io/premoweb/alpine-nginx-php7.3:latest",
                          "USER root",
                          "WORKDIR /var/www/html",
                          "RUN mkdir -p /var/www/html/dist",
                          "COPY backend/ /var/www/html/",
                          "COPY dist/ /var/www/html/dist/",
                          "RUN chown -R nobody.nobody /var/www/html",
                          "ENV NODE_ENV production",
                          "USER nobody",
                          "ENV PORT 8080",
                          "EXPOSE 8080",
                          "CMD [\"/usr/bin/supervisord\", \"-c\", \"/etc/supervisor/conf.d/supervisord.conf\"]"
                      ]
   }
```

Caprver can't build from the deploy.tar when pushed from Github Actions.

However, if I fetch the deploy.tar uploaded via Github Actions and drop it into the Deployment tab in the Caprover UI, it deploys with out any issue.

The error I'm getting is that dist/ does not exist.

I suspect a problem with my docker lines.

The goal is to copy the backend/ into /var/www/html and then copy the compiled (built) dist/ directory into /var/www/html/dist/.

This is where the universe begins to shred itself apart.
