### ISSUE TITLE
How to add service update config for MySQL

### ISSUE THREAD

**Issue by realskyrin** [caprover/caprover#1459]
**IMPORTANT:**
Please quickly search the existing issues and make sure that you're not create a duplicate issue. If you have a quesetion about a particular Dockerfile and deployment, change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

Please clearly state your question: **I want to add a startup command to MySQL App**

I tried to add the following configuration to the Service Update Override, but it doesn't work, is the config format incorrect?
```
TaskTemplate:
  ContainerSpec:
    Command:
      - "--max_connections"
    Args:
      - "500"
```
