### ISSUE TITLE
Making "Deploy to Caprover" Github Action an officially supported Caprover project

### ISSUE THREAD

**Issue by maietta** [caprover/caprover#1470]
I would like a project of mine to be considered for inclusion under the Caprover umbrella and namespace and to be included in the official docs. I would like change ownership from my company, to the Caprover project.

The project in question is a Github Action that is currently listed in the open Marketplace as "Deploy to PremoWeb" but in reality it will deploy to any Caprover host. I am building a version of Caprover for specialized hosting, which is why the name. It's built around Caprover and that's all that matters.

The Github Action is used as part of a deployment workflow to deploy specific files and directories to a Caprover host using "Method 1", using the App Token stored as a secret in the Github your repository along with two other secrets.

The secrets in Github a each project are "APP_NAME", "APP_TOKEN" and a project specific or global "CAPROVER_SERVER" secret.

The Github Action is listed in the marketplace as "Deploy to PremoWeb", found here: 
https://github.com/marketplace/actions/deploy-to-premoweb

And the project repo for the Github Action is located here:
https://github.com/PremoWeb/deploy-to-caprover

If this project looks like it could be beneficial to everyone,  then I propose the project get moved from PremoWeb to Caprover so the URL becomes something like this:

https://github.com/caprover/deploy-from-github

The workflow itself for each website or app would look something like this:

```
name: Build & Deploy

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            backend/
            frontend/dist/
            captain-definition
          outPath: deploy.tar

      - uses: premoweb/deploy-to-caprover@v1.0.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
```

However, I would like to do one more thing before the project is accepted (or after) is to merge the function of a7ul/tar-action@v1.1.0 into the deploy action so it looks more like this:

```

    ... build steps ... 
      - uses: caprover/deploy@1.0.0
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          files: |
            backend/
            frontend/dist/
            captain-definition
```
