### ISSUE TITLE
[Question] Deploy from private organisation github container registry 

### ISSUE THREAD

**Issue by tschannik** [caprover/caprover#1514]
Hi all,

I am trying to deploy a docker image from a private container registry owned by a github organisation account. I tried to add the registry in the cluster settings of caprover but no combination of url/password/account etc is working. 

Has anyone managed to connect a github org registry and teach me?

End goal is to build the image with a github action and deploy it with the caprover cli action.

Thanks in advance!

**Comment by maietta** [comment]
I literally just published exactly this, which you can find on the website.

I maintain a Github Action which uses the App Token method to deploy via the official CapRover CLI tool using a workflow file you add to your project.

Please see:
https://caprover.com/docs/ci-cd-integration/deploy-from-github.html

Also, feel free to join us on Slack (see website) if you have any specific questions for deployments.

**Comment by maietta** [comment]
Are you trying to deploy an app or build a docker image and then deploy to CapRover? CapRover offers a self-hosted registry. I fail to understand your logic.

If you are trying to deploy an app to CapRover via a Github project repository, then feel free to reference this guide: 

https://caprover.com/docs/ci-cd-integration/deploy-from-github.html

If you are trying to ask questions about how to build an image from GitHub, then this is unrelated to CapRover.

**Comment by githubsaturn** [comment]
@maietta  - I think your usecase is slightly different. What your script does is to create a tar file on Github and then send that to CapRover. The Docker image is still being built on CapRover's server.

On the contrary, what @tschannik  is trying to achieve is to pull the already-built docker image from github registry.

To do so, you'll have to go to Cluster > Add Docker Registry > Add your credentials.

Here is an example for one of my projects: I've changed the creds, but other than that, that's pretty much all I use. Free free to comment if you're still unable to connect.

![image](https://user-images.githubusercontent.com/10582082/190923201-9e0abad2-df31-48b2-af6e-4f2ae4344ebf.png)

**Comment by githubsaturn** [comment]
@maietta - unrelated to this thread:

I just realized that your [github action](https://github.com/caprover/deploy-from-github) and your [tutorial](https://caprover.com/docs/ci-cd-integration/deploy-from-github.html) are assuming deployment via tar file. While this works, it's suboptimal as you're not utilizing the [main benefit of using CI/CD](https://caprover.com/docs/ci-cd-integration.html#:~:text=This%20may%20result%20in%20a%20server%20crash%20when%20you%27re%20trying%20to%20build%20your%20source%20code%20on%20your%20own%20server.%20The%20best%20way%20to%20avoid%20these%20heavy%20loads%20is%20to%20build%20your%20Docker%20image%20elsewhere%20and%20just%20deploy%20the%20built%20artifact%20to%20your%20CapRover%20server) which is to save CapRover's CPU from having to build the docker image.

Have look at the [Gitlab tutorial](https://caprover.com/docs/ci-cd-integration/deploy-from-gitlab.html) and see how it's different. Feel free to upgrade the workflow and tutorial. Also, feel free to ask me any questions that you might have on Slack.

**Comment by maietta** [comment]
Thanks.

I guess that boils down to how the app is designed. In my example provided, I'm building the Vue 3 frontend within Github's CD/CI side of things, then packing up the file there. Technically, CapRover is also doing some CD/CI stuff because it's building the docker image locally, but it's minimal.

The added bonus to my strategy is that only the files needed to run the site are copied over for the final app deployment, not the entire source code from a branch.

I've seen a lot of people add things like composer within their Dockerfile to add their PHP dependencies. While this does work, I tend to believe it's better to include those dependencies within the repo itself and copy those as part of the app, using the composer tool locally in development instead of being part of CI/CD.

So I'm not sure what to call my strategy then or how I would go about documenting it.

**Comment by githubsaturn** [comment]
Yea I see your point, and that's totally valid.

But nothing prevents you to "also" build the image on Github and reduce the load on CapRover. 

All you need to do is to replace this step:
```

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            backend/
            frontend/dist/
            captain-definition
          outPath: deploy.tar
```

With these (very crude pseudo code):
- Copy all necessary files to a directory, say `temp-build`
- then run `docker build -t ghcr.io/resplab/yourorg/yourrepo:tag`
- then run `docker push ghcr.io/resplab/yourorg/yourrepo:tag`
- then replace the `-t tarfile.tar` with `--imageName ghcr.io/resplab/yourorg/yourrepo:tag`

That way, you'll get to benefit from both sides of the aisle: no unnecessary files, also no build load on CapRover server.

I'm using this approach for a project that I did, here is the workflow:
```yaml
name: Deploy APP

env:
  REACT_APP_API_URL: "__IGNORE__" # Not needed for API, just to make the build work
  CONTEXT_DIR: "./myappdirectory"
  IMAGE_NAME: ${{ github.repository }}/myappdirectory
  DOCKERFILE: Dockerfile.production
  CAPROVER_APP: myapp
  CAPROVER_HOST: https://SOMETHING
  DOCKER_REGISTRY: ghcr.io

on:
  push:
    branches:
      - master
    paths:
      - "myappdirectory/**"

jobs:
  publish-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
          export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
          echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Release to DockerHub
        shell: bash
        run: ./build_and_push.sh
      - name: Deploy to CapRover
        uses: floms/action-caprover@bc835272f3c1ec1a470d80d44fc2a4518eb85d9d
        with:
          host: ${{ env.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          image: "${{ env.FULL_IMAGE_NAME }}"
```

`build_and_push.sh`

```bash
#!/bin/bash

# Exit early if any command fails
set -e
pwd


# ensure you're not running it on local machine
if [ -z "$CI" ] || [ -z "$GITHUB_REF" ]; then
    echo "Running on a local machine! Exiting!"
    exit 127
else
    echo "Running on CI"
fi


cd $CONTEXT_DIR
env
# ls -lah

# dump all env vars in a temp file and pass it as build args
rm /tmp/build_args || echo OK
env > /tmp/build_args
echo "--build-arg \""`cat /tmp/build_args | sed -z 's/\n/" --build-arg "/g'`"IGNORE_VAR=IGNORE_VAR\"" >  /tmp/build_args

BUILD_ARGS=`cat /tmp/build_args`
COMMAND="docker build -t $FULL_IMAGE_NAME -t $IMAGE_NAME_WITH_REGISTRY:latest -f $DOCKERFILE $BUILD_ARGS --no-cache ."

echo "-------------------"
echo "-------------------"
echo $BUILD_ARGS
echo "-------------------"
echo $COMMAND
echo "-------------------"
echo "-------------------"

/bin/bash -c "$COMMAND"
docker push $IMAGE_NAME_WITH_REGISTRY:latest
docker push $FULL_IMAGE_NAME

rm /tmp/build_args
```
