### ISSUE TITLE
[Question] command property in One Click Apps' Template

### ISSUE THREAD

**Issue by sigefi-app** [caprover/caprover#1600]
Hello everyone, first of all thank the collaborators for this great tool.

I come to ask something that I don't know if it is enabled, or if it is possible. I used One Click Apps' Template option to slightly customize the yml used to create MySQL instances:

```yml
captainVersion: 4
services:
    $$cap_appname-db:
        image: mysql:$$cap_mysql_version
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        restart: always
        command:
            --authentication-policy=mysql_native_password
            --character-set-filesystem=utf8mb4
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_spanish_ci
            --default-authentication-plugin=mysql_native_password
            --default-time-zone="+00:00"
            --innodb-dedicated-server=OFF
            --long-query-time=3
            --skip-log-bin
            --skip-replica-start
            --slow-query-log
            --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_db_pass
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_mysql_version
          label: MySQL Version
          defaultValue: '8.0.31'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/library/mysql/tags/
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_db_pass
          label: MySQL Root password
          description: ''
          validRegex: /.{1,}/
    instructions:
        start: >-
            MySQL is the world's most popular open source database. With its proven performance, reliability and ease-of-use, MySQL has become the leading database choice for web-based applications, covering the entire range from personal projects and websites, via e-commerce and information services, all the way to high profile web properties including Facebook, Twitter, YouTube, Yahoo! and many more.
            After installation on CapRover, it will be available as srv-captain--YOUR_CONTAINER_NAME at port 3306 to other CapRover apps.
            Enter your MySQL Configuration parameters and click on next. It will take about a minute for the process to finish.
        end: "MySQL is deployed and available as srv-captain--$$cap_appname-db:3306 to other apps. For example with NodeJS, you do 'var con = mysql.createConnection({ host: 'srv-captain--$$cap_appname-db', user: 'root', password: '*********' });'"
    displayName: MySQL CM
    isOfficial: false
    description: MySQL is a relational database management system based on SQL
    documentation: Taken from https://docs.docker.com/compose/mysql/
```

The only change I made was to add a few configuration parameters via the `command` parameter, especially to modify the `sql_mode` (the others in there were from a docker-compose I had used before).

After doing so, I started mysql app and I saw that the `sql_mode` of the instance was not changed (executing `SELECT @@GLOBAL.sql_mode;`) and in fact it seems that it did not take any of the configuration parameters that I passed through `command`.

The question is: **Does CapRover ignore the command parameter?** Or maybe there is something additional that I can do that I'm not seeing.

Thanks!
