### ISSUE TITLE
Deploy from different branches to different apps using one github action?

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1605]
hi there, 

i have this situation here: 
an app wich has 3 branches: staging, testing and production. they have an actionfile in common wich does basically: 
-build a docker file
- push docker file to ghcr
- deploys image to caprover

this is how the action file looks: 

```
on:
  push:
      # branches: ['master']
      branches: ['staging', 'testing', 'production']


env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./web/Dockerfile
            image: ghcr.io/user/redwood-docker-compose-web
            appname: web
          - dockerfile: ./api/Dockerfile
            image: ghcr.io/user/redwood-docker-compose-api
            appname: api

    permissions:
      contents: read
      packages: write

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

    # checkout lates repository
      - name: Checkout repository
        uses: actions/checkout@v2

    # add .env file from github secret
    # this can be done in the caprover interface too!!!
    # https://github.com/caprover/caprover/discussions/1571
      - name: add .env file
        uses: DamianReeves/write-file-action@master
        with:
          path: api/db/.env
          contents: ${{ secrets.DB_STAGING }}
          write-mode: append
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
# from https://stackoverflow.com/questions/73599803/refer-to-docker-image-variable-name-in-github-action
      - name: Deploy image
        uses: floms/action-caprover@v1
        with:
          host: '${{ secrets.CAPROVER_SERVER }}'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          app: ${{ steps.branch-name.outputs.current_branch }}${{ matrix.appname }})
          image: ${{ steps.meta.outputs.tags }}

```

in caprover there are 6 apps: 
stagingweb, stagingapi
testingapi, testingweb
productionweb, productionapi

so the plan would be to send the correct docker image to the correct app in caprover (the secondlast line generates names from branchname and appname (web | api)

but still i do get the error message that the specific app does not exist on my caprover instance: 

```
reparing deployment to CapRover...

Ensuring authentication...
stagingweb) app not exist on this CapRover machine.
```
(this is the action log)

wich is weird, because there clearly is a "stagingweb" app in caprover. 

What am i missing here? 

any idea would be great!
