### ISSUE TITLE
possibility to add a flag after a one-click-apps deployment ?

### ISSUE THREAD

**Issue by frelle** [caprover/caprover#1679]
Hello

First, again, thank you for this repo, which helps many no-docker experts to deploy quickly an app.

So here my question: I installed the app "**listmonk**" (available in one-click-app). During the setup, I have not configured the last part "**Optional Listmonk flags**".

The app was created successfully. I'm using in production.

Now, I need to use this feature (Optional Listmonk flags) that I did not setup. I already created a new persistent folder. 

1. is-it possible to do that now ? or do I need to reinstall? 
2. from what I understood, maybe an option is to use the feature in the App Configs Tab called "Service Update Override". The following content is what needed or it's a mistake? 

```
TaskTemplate:
  ContainerSpec:
    Command: 
      - "listmonk"
    Args:
      - "--static-dir=my/custom/path"
```

Thank you for any help!
