### ISSUE TITLE
Cannot revert to a previous deploy, 

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#1704]
Hi, 

i have just realized that i cannot revert to a previous deploy when using the Caprover WebUI
![Bildschirmfoto vom 2023-03-15 10-55-13](https://user-images.githubusercontent.com/1011875/225274875-00ade565-fc80-421a-be15-68230393b834.png)

i have set up caprover with its own docker registry. to do that i created a new app, and deployed "registry:2" to it, the registry config file looks like so: 
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

```

in caprover i have added the registy like so: 
![Bildschirmfoto vom 2023-03-15 11-02-57](https://user-images.githubusercontent.com/1011875/225276043-fc29a3c2-6948-4035-b467-fcaf4f4fa7ae.png)

to deploy the app i use a github action workflow like this (its only the deploy part of the action file): 

```
    steps:
      # Log in to the container registry
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      # Deploy the image
      - name: Deploy image
        uses: floms/action-caprover@v1
        with:
          host: "${{ secrets.CAPROVER_SERVER }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          app: ${{ steps.branch-name.outputs.current_branch }}${{ matrix.appname }}
          image: ${{ steps.meta.outputs.tags }}
```

so back to the problem: when i click on revert, caprover just reverts to the current running version. it does not go back in time. 
what can be the problem here? 

thank you so much!
