### ISSUE TITLE
App Deployment Help: Cryptpad

### ISSUE THREAD

**Issue by SpaceIgniter** [caprover/caprover#1747]
Greetings, hope you are doing well.

My environment is:
Windows Docker Desktop
Ubuntu WSL 2
Caprover installed on Localhost.

Caprover works perfectly fine and so does the One Click Apps. I'm not winning with 'manually' creating and deploying Apps however.

I've tried to install Cryptpad with their Docker documentation, using it in Caprover.

I get errors and the build fails if I deploy from their Dockerfile, so I'm not sure if I'm using the correct file. I can't deploy via Github, since Caprover is not linked to a public domain, it's a Local install.

I'm still learning  so I don't have the answers at this stage. 

Any assistance or how to guide to install Cryptpad will be appreciated. I will use this guide as a template/base for any other manual install in future. 

Thank you.

**Comment by githubsaturn** [comment]
I don't know what Cryptpad is. But regardless, you can deploy any app on CapRover as long as is deployable on Docker.

I just did a quick search and I found [this docker compose file](https://github.com/xwiki-labs/cryptpad-docker/blob/main/docker-compose.yml). I made a few edits to make it compatible with CapRover:

```yaml
captainVersion: 4
caproverOneClickApp:
    instructions:
        start: Just a plain Docker Compose.
        end: Docker Compose is deployed.

services:
  cryptpad:
    image: promasu/cryptpad:nginx

    environment:
      - CPAD_MAIN_DOMAIN=example.com
      - CPAD_SANDBOX_DOMAIN=sandbox.example.com
      - CPAD_HTTP2_DISABLE=true

    volumes:
      - data-blob:/cryptpad/blob
      - data-block:/cryptpad/block
      - data-customize:/cryptpad/customize
      - data-data:/cryptpad/data
      - data-files:/cryptpad/datastore
      - data-config-js:/cryptpad/config/config.js
```
