### ISSUE TITLE
[Question] Unable to access host IP address from Caprover's Nginx reverse proxy when using network_mode: host

### ISSUE THREAD

**Issue by Alfagun74** [caprover/caprover#1773]
**Issue Description:**
I am currently running a container of Home-Assistant on my host using Docker Compose with `network_mode: host` configuration, which allows it to have access to my local network and devices such as smart plugs. To make Home-Assistant available from the internet, I would use a Caprover Nginx reverse proxy container, [which is the usual setup](https://github.com/caprover/caprover/issues/1371). However, I am facing difficulties in accessing the host IP address from Caprover's Nginx reverse proxy due to the limitation of `network_mode: host`.

**Steps to Reproduce:**
1. Set up a Home-Assistant container on the host.
```yaml
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    network_mode: host
networks:
   default:
     external:
       name: captain-overlay-network
```
3. Deploy a Caprover Nginx reverse proxy container pointing to ``http://homeassistant:8123``.
4. Attempt to access the Home-Assistant instance from the internet using the Caprover reverse proxy URL.

**Expected Behavior:**
I expect to be able to access the Home-Assistant container through the Caprover Nginx reverse proxy.

**Actual Behavior:**
502 Bad Gateway.

What am i doing wrong?
