### ISSUE TITLE
CaprOver unable to get docker image from GitHub

### ISSUE THREAD

**Issue by AaronHessler** [caprover/caprover#1795]
I want to deploy my Svelte Kit app using Github actions, but CapRover seems to be unable to get the image. Here is the error;
`Error: (HTTP code 500) server error - Head "https://ghcr.io/v2/omikronone/bubble/manifests/latest": unauthorized`
Here is my workflow:

```
name: build + publish

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true
      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://cap.omikron.me
          app: 'bubble'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/omikronone/bubble:latest'

```

I have already tried to add the following to the definitions of my app:
`{
  "schemaVersion": 2,
  "version": "1.0",
  "image": {
    "name": "ghcr.io/omikronone/bubble:latest",
    "authToken": "$CR_PAT"
  },
  "routes": [
    {
      "path": "/",
      "port": 80
    }
  ]
}
`
`$CR_PAT` is my personal access token declared in the env variables.

But didn't work either.
What am I supposed to do?
