### ISSUE TITLE
[Deployment Issue] Build & Deploy from Github unauthorized

### ISSUE THREAD

**Issue by yalihart** [caprover/caprover#1818]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

### What is the problem?
Using Github Workflow `Build & Deploy` as shown [here](https://caprover.com/docs/ci-cd-integration/deploy-from-github.html#alternative-method-more-efficient), the Github action is successful but CapRover Deployment failed: 
```sh
------------------------- Thu Jul 27 2023 13:35:10 GMT+0000 (Coordinated Universal Time)
Build started for project-name-omitted
An explicit image name was provided (ghcr.io/yalihart/project-name-omitted:e892417). Therefore, no build process is needed.
Pulling this image: ghcr.io/yalihart/project-name-omitted:e892417 This process might take a few minutes.
Build has failed!
----------------------
Deploy failed!
Error: (HTTP code 500) server error - Head "https://ghcr.io/v2/yalihart/project-name-omitted/manifests/e892417": unauthorized
```
#### If applicable, content of `captain-definition` file:
```json
 {
  "schemaVersion": 2,
  "dockerfilePath": "./Dockerfile"
 }
```

#### Steps to reproduce the problem:
1. Create a CapRover app
2. Create a private Git repo
3. Add the following secrets to the repo:
```
APP_NAME: Name of the app in CapRover
APP_TOKEN: App token from the CapRover app
CAPROVER_SERVER: URL of your CapRover Server
GH_TOKEN: GitHub Personal Access with write permission for packages.
```

4.  
<details>
  <summary>Add the following Github action:</summary>

```yaml
name: Build and Deploy Docker Image

on: [ pull_request, push ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}
```
</details>
5. Check your apps build logs on CapRover

#### Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```
```sh
Linux ubuntu 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
               total        used        free      shared  buff/cache   available
Mem:           7.7Gi       641Mi       1.3Gi       3.0Mi       5.8Gi       6.8Gi
Swap:             0B          0B          0B
```
