### ISSUE TITLE
uvdesk ... not working

### ISSUE THREAD

**Issue by lionux2** [caprover/caprover#1950]
Following the template for one-click deployment based on this posting of UVdesk: https://mariushosting.com/how-to-install-uvdesk-on-your-synology-nas/

Yet, my template does not work ... what is then so wrong?

```
captainVersion: 4
services:
    $$cap_appname-db:
        image: mysql:$$cap_database_version
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_db_pass
            MYSQL_DATABASE: uvdesk
            MYSQL_USER: $$cap_db_user
            MYSQL_PASSWORD: $$cap_db_pass
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        depends_on:
            - $$cap_appname-db
        image: nuttcorp/uvdesk:$$cap_version
        restart: always
        environment:
            MYSQL_USER: $$cap_db_user
            MYSQL_PASSWORD: $$cap_db_pass
            MYSQL_ROOT_PASSWORD: $$cap_db_pass
            MYSQL_DATABASE: uvdesk
caproverOneClickApp:
    variables:
        - id: $$cap_db_user
          label: Database user
          defaultValue: uvuser
          validRegex: /^([a-zA-Z0-9])+$/
        - id: $$cap_db_pass
          label: Database password
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_version
          label: UVdesk Version
          defaultValue: 'latest'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/library/UVdesk/tags/
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_database_version
          label: Database Version, default is MySQL
          defaultValue: '5.7'
          description: Check out the Docker pages for the valid tags https://hub.docker.com/r/library/mysql/tags/ or https://hub.docker.com/_/mariadb?tab=tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            UVdesk is an open-source helpdesk system that allows businesses to manage their customer support and communication efficiently. It provides a ticketing system that helps organizations handle customer inquiries, issues, and support requests in a structured manner.
            Enter your UVdesk Configuration parameters and click on next. A MySQL (database) and a UVdesk container will be created for you.  The process will take about a minute for the process to finish.
        end: >
            UVdesk is deployed and available as $$cap_appname-UVdesk . 
             IMPORTANT: It will take up to 2 minutes for UVdesk to be ready. Before that, you might see a 502 error page.
    displayName: UVdesk
    isOfficial: true
    description: UVdesk is a content management system based on PHP and MySQL that is usually used with the MySQL or MariaDB database
    documentation: Taken from https://docs.docker.com/compose/UVdesk/. 
```
