### ISSUE TITLE
How to bind/publish port to IPv6 address?

### ISSUE THREAD

**Issue by shantanoo** [caprover/caprover#1955]
Using docker CLI, one can use following format for publishing port to IPv6 (https://forums.docker.com/t/publish-port-to-specific-ipv6-address/101701/2)

`-p [ipv6]:8080:80`

How to achieve it in Captain Rover WebUI?

**Comment by githubsaturn** [comment]
Short answer: Not possible via web UI.

It's not supported by design. [CapRover's goal](https://github.com/caprover/caprover/blob/master/CONTRIBUTING.md#important-caprover-goals--scope) is to only cover the most common usecases via its webUI. Other use cases, can be done via overrides.

CapRover does not use Docker CLI to communicate to Docker. Instead it uses Docker API.

You can use [Service Update Override](https://caprover.com/docs/service-update-override.html#schema) to customize the service updates. 

I'm not sure if Docker's API allow you to bind to IPv6, but probably try something like this:
```yaml
EndpointSpec:
  Mode: vip
  Ports:
    - Name: something
      Protocol: tcp
      TargetPort: 80
      PublishedPort: [ipv6]:8080
      PublishMode: host
```

If it doesn't work, you can ask [Docker's github page](https://github.com/moby/moby) on how IPv6 can be supported using their API.
