### ISSUE TITLE
Extend one-click-templates to support service update overrides

### ISSUE THREAD

**Issue by adamshand** [caprover/caprover#1960]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to have one-click-apps mount remote storage as a Docker volume.  For example, there is a [Rclone plugin for Docker](https://rclone.org/docker/) which allows the mounting of S3 buckets inside of containers.  This allows containers which require persistent storage to be moved (or fail over) between swarm nodes.

More details at: https://github.com/caprover/caprover/discussions/1956

**Describe the solution you'd like**

CapRover supports remote volumes via service update overrides, eg.

```
TaskTemplate:
  ContainerSpec:
    Mounts:
      - Type: volume
        Source: memos-rclone-b2
        Target: /var/opt/memos
        VolumeOptions: 
          DriverConfig:
            name: rclone
            Options:
              remote: b2:applications/memos
              vfs-cache-mode: full
```

However, there is currently no way to include a service override inside a one-click-app template.  

If one-click-app templates were extended to support service overrides, this would allow easy provisioning of apps which require persistent storage in a way which also allows fail over between swarm nodes.
