### ISSUE TITLE
Immich One Click Apps Latest Version Problem

### ISSUE THREAD

**Issue by burak-sayici** [caprover/caprover#1985]
Hello, I use CapRover very fondly. I saw the immich application while browsing in the once click apps section in the application and I immediately installed it excitedly. But there was a problem like this: CapRover was installing the v1.52.1 version of the immich application, but the mobile version of the immich application did not see the server because the version was old. Firstly, I tried hard to install the current version of the immich application from the first click apps section. I wrote v1.92.1 in the immich verison section, but it did not install. After installing version 1.52.1, I tried to install the current version from the deployment tab, but it was not successful again. As a last resort, I performed manual installation using docker compose all services "captain-overlay-network" and I saw that I could access my server's local ip address (192.168.1.60) from port 2283. Even though I tried to connect it to my domain with Nginx Reverse Proxy application via CapRover, I was not successful. I made many attempts to the address and port section (http://$:2283, http://$:3001, http://0.0.0.0:2283, http://0.0.0.0:2283, http://192.168.1.60:2283) but I did not get any successful results.
I couldn't complete the installation successfully both because I couldn't install the current version as one click apps and because I couldn't do reverse proxy with docker compose. It only works on my local network. I would like to ask for your support on the subject.

docker-compose.yml:

```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    networks:
      - captain-overlay-network
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    networks:
      - captain-overlay-network
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - captain-overlay-network
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    networks:
      - captain-overlay-network
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - captain-overlay-network
    restart: always

volumes:
  pgdata:
  model-cache:

networks:
  captain-overlay-network:
    external: true
```

docker ps:
![image](https://github.com/caprover/caprover/assets/155234322/f92e69a5-13e2-4dd7-94d8-e1a993098578)

NGINX Reverse Proxy:
![image](https://github.com/caprover/caprover/assets/155234322/f3572f6a-694d-483c-92ee-ec38bf209a80)

Local access:
![image](https://github.com/caprover/caprover/assets/155234322/38121370-c85d-466e-b5b6-d798097c9c27)
