### ISSUE TITLE
Lobe-Chat One-Click App Deployment Help / New Add

### ISSUE THREAD

**Issue by crxssrazr93** [caprover/caprover#2030]
Hi,

I am trying to deploy Lobe-Chat following instructions [here](https://chat-docs.lobehub.com/en/self-hosting/platform/docker) and the official instructions for One-Click Deployment, but I am not able to access the app.

Here's the template I used:

```
captainVersion: 4
services:
    $$cap_appname:
        image: $$cap_image
        ports:
            - "$$cap_ports"
        environment:
            OPENAI_API_KEY: $$cap_openai_key
            ACCESS_CODE: $$cap_access_code
        restart: always

caproverOneClickApp:
    variables:
        - id: $$cap_appname
          label: Appname
          description: Enter your application name
          validRegex: /^[a-zA-Z0-9_-]+$/
        - id: $$cap_ports
          label: Ports
          description: Enter the port mapping (host:container)
          defaultValue: "3210:3210"
          validRegex: /^[0-9]+:[0-9]+$/
        - id: $$cap_openai_key
          label: OpenAI Key
          description: Enter your OpenAI API key
          validRegex: /.{1,}/
        - id: $$cap_access_code
          label: Access Code
          description: Enter your access code
          validRegex: /.{1,}/
        - id: $$cap_image
          label: Image
          description: Enter the Docker image name (including the repository if applicable)
          defaultValue: lobehub/lobe-chat:latest
          validRegex: /^[a-zA-Z0-9\/\-_.:]+$/
    instructions:
        start: "Enter your app configuration parameters and click on next. The process will take about a minute for the container to be created."
        end: "Your application is deployed and available as $$cap_appname. Please wait for a moment for the service to be fully ready."
    displayName: Custom Application
    isOfficial: false
    description: Docker container for a custom application
    documentation: "Port mapping is set up according to user input. Environment variables for OpenAI API key and access code are configured."
```

Any thoughts on what might have gone wrong?

Thanks.

**Comment by githubsaturn** [comment]
Don't use port mapping, use containerHttpPort
```yaml

captainVersion: 4
services:
    $$cap_appname:
        image: lobehub/lobe-chat
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            ACCESS_CODE: $$cap_ACCESS_CODE
            OPENAI_API_KEY: $$cap_OPENAI_API_KEY
        caproverExtra:
            containerHttpPort: '3210'
caproverOneClickApp:
    variables:
        - id: $$cap_OPENAI_API_KEY
          label: cap_OPENAI_API_KEY
          description: cap_ACCESS_CODE
        - id: $$cap_ACCESS_CODE
          label: cap_ACCESS_CODE
          defaultValue: 'cap_ACCESS_CODE'
    instructions:
        start: |-
            Chat app.
    displayName: Chat
    isOfficial: true
    description: description
```
