### ISSUE TITLE
Volumes wont attatch

### ISSUE THREAD

**Issue by patpatwithhat** [caprover/caprover#2054]
I use Caprover to host an ASP .Net 8 app.
I have a Docker Compose File like this:
```
version: '3.3' 

services:
  srv-captain--medicore:  
    image: medicore:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - medicore_volume:/app/wwwroot/images

volumes:
  medicore_volume: {}

```

Sadly, my volume never gets created; therefore, I can never access the data in app/wwwroot/images.
Also creating the volume before I run the app with Caprover doesn't change anything.
Any suggestions?
If I run the same container directly on my server without Caprover involved, I can create the volume with no problems like this:
```
docker run -d     -v medicore_volume:/app/wwwroot/images     --name MediCore     mediocre:latest
```

These are my specs
```
Linux v2202309205877238071 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
              gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
Speicher:      3,8Gi       1,0Gi       292Mi        63Mi       2,5Gi       2,5Gi
Swap:             0B          0B          0B
```
