### ISSUE TITLE
Net Core 8.0 github actions deploy

### ISSUE THREAD

**Issue by carlosdevelops** [caprover/caprover#2060]
Hey guys I am having issues deploying through github when I deploy with tarball it works fine but when I setup this file it always fails at this line below any help is appreciated

Run dotnet build --configuration Release --no-restore
  
/home/runner/.dotnet/sdk/8.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. 

```
name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0' ]  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      - name: Publish the application
        run: dotnet publish -c Release -o ./publish

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./publish

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'  # Your CapRover server URL
          app: '${{ secrets.APP_NAME }}'  # Your CapRover app name
          token: '${{ secrets.APP_TOKEN }}'  # Your CapRover app token
          source: app

```
