### ISSUE TITLE
[Deployment Issue] 'Captain-definition file does not exist' after updating repo structure

### ISSUE THREAD

**Issue by TylerWanta** [caprover/caprover#2068]
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?
Previously my repo only had a single .net core project in it and structure looked like this
```
- VaulticServer\
----- captain-definition
----- other files
```

The deploy for it worked and all was ok. But, In order to improve the app structure, I split it out into multiple projects like so:
```
- VualticServer\
----- API\
---------- captain-definition
---------- other files
----- STS\
----------- captain-definition
----------- other files
----- Business\
----------- other files
```

The plan being that each project with a captain-definition will get its own caprover app. I use github actions and thought I would be able to just update the path to point to the new apps directory and life would be good but its not working. 

Previous action (works)
```
name: Build & Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "../"
          files: |
            ./VaulticServer
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
```

New action (works but causes `Captain Definition file does not exist` in caprover)
```
 name: Build & Deploy API

on:
  workflow_dispatch:

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "../"
          files: |
            ./VaulticServer/API
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
```
Note: I even tried specifying the captain-definition file like so:
```
  - uses: a7ul/tar-action@v1.1.0
    with:
      command: c
      cwd: "../"
      files: |
        ./VaulticServer/API
        ./VaulticServer/API/captain-definition
      outPath: deploy.tar
```
the github action still succeeds but same error in caprover. I tried the advice from [this](https://github.com/caprover/caprover/issues/109) question and ran

`git archive --format tar --output ./test.tar refactorRepo`. This gave me a tar folder with the correct file structure, i.e.
```
- test.tar
----- captain-definition
----- other files
```
I've also double checked to make sure that the captain-definition is in fact pushed to my branch. 

If applicable, content of `captain-definition` file:
```
 {
  "schemaVersion" :2 ,
  "dockerfilePath" :"./Dockerfile"
 }
```
my docker file is pretty simple as well 
(old)
```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# build runtime image
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "VaulticServer.dll"]
```
updated (only changed the .dll name)
```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# build runtime image
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "API.dll"]
```

Steps to reproduce the problem:
Not entirely sure. Maybe its just an issue with a nested folder structure? 

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

```
Linux caprover1111onubuntu2004-s-2vcpu-2gb-90gb-intel-nyc3-01 5.4.0-162-generic #179-Ubuntu SMP Mon Aug 14 08:51:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
              total        used        free      shared  buff/cache   available
Mem:          1.9Gi       913Mi       127Mi        60Mi       930Mi       808Mi
Swap:            0B          0B          0B
```

**Comment by githubsaturn** [comment]
Try this one, does it work?
```
      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            API/
          outPath: deploy.tar
```
