### ISSUE TITLE
caprover/deploy-from-github can I just tag latest?

### ISSUE THREAD

**Issue by VictorioBerra** [caprover/caprover#2116]
GitHub only gives me 500MB of free packages storage. Im worried if I generate lots of images with every single push I will hit my limits pretty quick.

here is my current GitHub Actions YAML:

```yaml
name: Deploy to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          image_tag: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

I am looking at the docs here: https://caprover.com/docs/ci-cd-integration/deploy-from-github.html

I see the docs recommend using the first 7 characters of the commit SHA, often used as a tag for the Docker image.

If I use latest will that still work OK? Or might it somehow push the older version somehow?
