### ISSUE TITLE
[Deployment] 'Error: Captain Definition file does not exist' when deploying multiple Docker images

### ISSUE THREAD

**Issue by tonyzamyatin** [caprover/caprover#2138]
Hi guys! Kinda struggeling and need your help :)

## Issue summary
I'm facing a deployment issue with CapRover when trying to deploy multiple distinct Docker images to their respective apps. The GitHub Actions workflow builds and pushes the images to the GitHub Container Registry successfully, but the deployment on CapRover fails with the following error:
```
Build started for quizard-backend-api
Build has failed!
----------------------
Deploy failed!
Error: Captain Definition file does not exist!
```

## Project structure
I have the follwing project structure:
```
my-project/
│
├── .github/
│   └── workflows/
│       └── caprover-deploy.yml
│
├── backend/
│   └── Dockerfile
│   └── ...
│
├── frontend/
│   └── Dockerfile
│   └── ...
```
## Steps tried
I closely follow the [guide for CI/CD via GitHub ](https://caprover.com/docs/ci-cd-integration/deploy-from-github.html#alternative-method-more-efficient). Unfortunately, the `caprover/deploy-from-github@v1.1.2` apparently does not work with private repositories (as far as I tried). I found a similar issue (#360) and tried the [two alternative methods](https://github.com/caprover/caprover/issues/360#issuecomment-460023070) which both result in the error:
1. **Use git webhooks:** I use a single `caprover-releases` branch, because I have multiple `caprover-defintion` files with unique suffixes (see first workflow below). I surmise that CapRover might not recognize as valid `caprover-definition` files.
2. **Use CapRover API:** I use curl to directly make an POST request to the CapRover API at the end of each image build. In the bode I send a `caprover-definition` file containing the Docker image URL (see second workflow below).

### Method 1: Git webhooks:
1. Create a GitHub repo
2. Generate a new ssh key with the command specified in [Deployment Methods guide](https://caprover.com/docs/deployment-methods.html):
  ```
  ssh-keygen -m PEM -t ed25519 -C "yourname@example.com" -f ./deploykey -q -N ""
  ```
3. Add the public key as a new deploy key for the GitHub repo (Settings -> Deploy keys -> Add deploy key)
5. Setup multiple apps on CapRover dashboard
7. In  the *Deploy* rab go to *Deploy from Github/Bitbucket/Gitlab* and add GitHub repo URL, branch name and private key generate in step 2.
8. Copy webhook URL generated by CapRover
9. Create a new GitHub webhook with the URL generated in the last step
10. Repeat steps 7-9 for each app.
11. Recreate my GitHub actions workflow and set the workflow `env` variables and GitHub repo secrets:
```
name: Build and Deploy MyApp Components

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  CAPROVER_BRANCH: caprover-releases

jobs:
  # Job for API app
  build-and-deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Preset Image Name for API
        run: echo "IMAGE_API_URL=${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/myapp-api:backend-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push API Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_API_URL }}

      - name: Set Git User for Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Switch to caprover-releases branch and update captain-definition for API
        run: |
          git checkout -b ${{ env.CAPROVER_BRANCH }} || git checkout ${{ env.CAPROVER_BRANCH }}
          git fetch origin
          git reset --hard origin/${{ env.CAPROVER_BRANCH }}
          echo '{
            "schemaVersion": 2,
            "imageName": "${{ env.IMAGE_API_URL }}"
          }' > captain-definition-api
          git add captain-definition-api
          git commit -m "Update captain-definition for API deployment"
          git push origin ${{ env.CAPROVER_BRANCH }}

  # Job for Worker app
  build-and-deploy-worker:
    runs-on: ubuntu-latest
    needs: build-and-deploy-api

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Preset Image Name for Worker
        run: echo "IMAGE_WORKER_URL=${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/myapp-worker:backend-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Worker Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_WORKER_URL }}

      - name: Set Git User for Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Switch to caprover-releases branch and update captain-definition for Worker
        run: |
          git checkout -b ${{ env.CAPROVER_BRANCH }} || git checkout ${{ env.CAPROVER_BRANCH }}
          git fetch origin
          git reset --hard origin/${{ env.CAPROVER_BRANCH }}
          echo '{
            "schemaVersion": 2,
            "imageName": "${{ env.IMAGE_WORKER_URL }}"
          }' > captain-definition-worker
          git add captain-definition-worker
          git commit -m "Update captain-definition for Worker deployment"
          git push origin ${{ env.CAPROVER_BRANCH }}

  # Job for Frontend app
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build --verbose
        working-directory: ./frontend

      - name: Preset Image Name for Frontend
        run: echo "IMAGE_FRONTEND_URL=${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/myapp-frontend:frontend-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_FRONTEND_URL }}

      - name: Set Git User for Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Switch to caprover-releases branch and update captain-definition for Frontend
        run: |
          git checkout -b ${{ env.CAPROVER_BRANCH }} || git checkout ${{ env.CAPROVER_BRANCH }}
          git fetch origin
          git reset --hard origin/${{ env.CAPROVER_BRANCH }}
          echo '{
            "schemaVersion": 2,
            "imageName": "${{ env.IMAGE_FRONTEND_URL }}"
          }' > captain-definition-frontend
          git add captain-definition-frontend
          git commit -m "Update captain-definition for Frontend deployment"
          git push origin ${{ env.CAPROVER_BRANCH }}

```

The workflow passes, but the CapRover deployment fails with the error (see very top).

### Method 2: CapRover API
1. Create a GitHub repo
2. Create multiple apps in CapRover
3. Add and run the following workflow:
```
name: Build and Deploy My Apps

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  CAPROVER_SERVER: https://your-caprover-server-url
  CAPROVER_API_APP_NAME: my-backend-api
  CAPROVER_WORKER_APP_NAME: my-backend-worker
  CAPROVER_FRONTEND_APP_NAME: my-frontend

jobs:
  # Job for API app
  build-and-deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Preset Image Name for API
        run: echo "IMAGE_API_URL=${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/my-backend-api:$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push API Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_API_URL }}

      - name: Deploy API Image to CapRover via API
        run: |
          auth_token=$(curl -s -X POST \
              -H "Content-Type: application/json" \
              -d '{"password":"${{ secrets.CAPROVER_PASSWORD }}"}' \
              ${{ env.CAPROVER_SERVER }}/api/v2/login | jq -r '.token')

          curl -X POST \
            -H "X-Captain-Auth: $auth_token" \
            -H "x-namespace: captain" \
            -H "Content-Type: application/json" \
            -d '{
                  "captainDefinitionContent": "{\"schemaVersion\":2,\"imageName\":\"${{ env.IMAGE_API_URL }}\"}",
                  "gitHash": ""
                }' \
            ${{ env.CAPROVER_SERVER }}/api/v2/user/apps/appData/${{ env.CAPROVER_API_APP_NAME }}

  # Job for Worker app
  build-and-deploy-worker:
    runs-on: ubuntu-latest
    needs: build-and-deploy-api  # Run after API job

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Preset Image Name for Worker
        run: echo "IMAGE_WORKER_URL=${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/my-backend-worker:$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Worker Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_WORKER_URL }}

      - name: Deploy Worker Image to CapRover via API
        run: |
          auth_token=$(curl -s -X POST \
              -H "Content-Type: application/json" \
              -d '{"password":"${{ secrets.CAPROVER_PASSWORD }}"}' \
              ${{ env.CAPROVER_SERVER }}/api/v2/login | jq -r '.token')

          curl -X POST \
            -H "X-Captain-Auth: $auth_token" \
            -H "x-namespace: captain" \
            -H "Content-Type: application/json" \
            -d '{
                  "captainDefinitionContent": "{\"schemaVersion\":2,\"imageName\":\"${{ env.IMAGE_WORKER_URL }}\"}",
                  "gitHash": ""
                }' \
            ${{ env.CAPROVER_SERVER }}/api/v2/user/apps/appData/${{ env.CAPROVER_WORKER_APP_NAME }}

  # Job for Frontend app
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Frontend
        run: npm run build --verbose
        working-directory: ./frontend

      - name: Preset Image Name for Frontend
        run: echo "IMAGE_FRONTEND_URL=${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/my-frontend:$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend  
          file: ./frontend/Dockerfile  
          push: true
          tags: ${{ env.IMAGE_FRONTEND_URL }}

      - name: Deploy Frontend Image to CapRover via API
        run: |
          auth_token=$(curl -s -X POST \
              -H "Content-Type: application/json" \
              -d '{"password":"${{ secrets.CAPROVER_PASSWORD }}"}' \
              ${{ env.CAPROVER_SERVER }}/api/v2/login | jq -r '.token')

          curl -X POST \
            -H "X-Captain-Auth: $auth_token" \
            -H "x-namespace: captain" \
            -H "Content-Type: application/json" \
            -d '{
                  "captainDefinitionContent": "{\"schemaVersion\":2,\"imageName\":\"${{ env.IMAGE_FRONTEND_URL }}\"}",
                  "gitHash": ""
                }' \
            ${{ env.CAPROVER_SERVER }}/api/v2/user/apps/appData/${{ env.CAPROVER_FRONTEND_APP_NAME }}

```

## Server details
```
root@quizard-demo:~# uname -a && lsb_release -a && free -h
Linux quizard-demo 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
               total        used        free      shared  buff/cache   available
Mem:           3.7Gi       831Mi       269Mi        37Mi       3.0Gi       2.9Gi
Swap:             0B          0B          0B
```

Any guidance or suggestions would be much appreciated! Thanks!
