### ISSUE TITLE
Support Docker compose

### ISSUE THREAD

**Issue by githubsaturn** [caprover/caprover#2175]
**Is your feature request related to a problem? Please describe.**
I know there has been many requests on supporting Docker Compose. But the more I think about it, the more I realize Docker Compose is such a bad model for deploying apps that will be a recipe for disaster. 

Imagine this case:

```yml
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
```

In this case, you want to deploy the content of `./conf.d` in your local directory to CapRover. You may want to make a change, redeploy it again and you expect the new changes to be reflected.

Now, let's review another one:

```yml
version: '3.8'

services:
  mysql:
    image: my-image-uploader-app
    ports:
      - "8080:80"
    volumes:
      - ./uploaded-photos:/app/uploaded-photos
```

In this case, you DO NOT want the content of `./uploaded-photos` to be uploaded to your server. You just want to redeploy the image (and potentially the env values) when you deploy the new version to CapRover. 

So here is the challenge! Which model should we follow? The second model is obviously the "portable" one that that is what is used by One Click apps at this point. But it completely contradicts with the first model - going back to my original statement that "Docker compose is great to get the skeleton up, but for future deploys it should NOT be used."

Wanted to open this thread to hear the thoughts.
