### ISSUE TITLE
[Question]  Does caprover injects environment variables defined in captain-definition ?

### ISSUE THREAD

**Issue by ihsaddamhussain** [caprover/caprover#2178]
I am using github actions to deploy the application. below is my captain-definition file. But when the app is deployed, it skips the environment variables defined in captain-definition. Any advices will be highly appreciated

```json
{
  "schemaVersion": 2,
  "imageName": "postgres:latest",
  "instanceCount": 1,
  "envVars": [
    {
      "key": "POSTGRES_USER",
      "value": "myuser"
    },
    {
      "key": "POSTGRES_PASSWORD",
      "value": "mypassword"
    },
    {
      "key": "POSTGRES_DB",
      "value": "mydatabase"
    }
  ],
  "volumes": [
    {
      "containerPath": "/var/lib/postgresql/data",
      "hostPath": "/var/lib/captain/postgresql-data"
    }
  ]
}
```

and here is my deploy code

```yml
name: Build and Deploy Apps

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/postgres/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - postgres

    env:
      CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
      CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
      CAPROVER_APP_NAME: ${{ matrix.app }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up CapRover CLI
        run: npm install -g caprover

      - name: Check if ${{ matrix.app }} App Exists and Create
        run: |
          caprover apps list --caproverUrl ${{ env.CAPROVER_SERVER }} --caproverPassword ${{ env.CAPROVER_PASSWORD }} | grep -q "${{ env.CAPROVER_APP_NAME }}" || caprover api --caproverUrl ${{ env.CAPROVER_SERVER }} --caproverPassword ${{ env.CAPROVER_PASSWORD }} --path "/user/apps/appDefinitions/register" --data '{"appName": "${{ env.CAPROVER_APP_NAME }}", "hasPersistentData": true}'  --method POST   

      - name: Deploy ${{ matrix.app }} to CapRover Server
        run: |
          caprover deploy -c apps/${{ env.CAPROVER_APP_NAME }}/captain-definition --caproverUrl ${{ env.CAPROVER_SERVER }} --caproverPassword ${{ env.CAPROVER_PASSWORD }} --appName ${{ env.CAPROVER_APP_NAME }}
```
