### ISSUE TITLE
Can't delete an app that was created using a custom template

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [caprover/caprover#2181]
What is the problem?

I "failed" to created an app using a docker compose file due to missing volumes. The app still shows up in the app list and I can't delete it. I get an error saying that the confirmation text doesn't match.
(Sidenote: The name I entered for the app wasn't used but instead the name of the first service. I did try the app name that I actually used too though and still got the same error.)

Steps to reproduce the problem:

1. Create a one click app using template with the following code: 
```
captainVersion: 4
caproverOneClickApp:
    instructions:
        start: Just a plain Docker Compose.
        end: Docker Compose is deployed.
########
version: "3"

services:
  #traefik:
  #  image: "traefik:v2.9"
  #  container_name: "traefik"
  #  command:
  #    - "--log.level=DEBUG"
  #    - "--api.insecure=true"
  #    - "--providers.docker=true"
  #    - "--providers.docker.exposedbydefault=false"
  #    - "--entrypoints.web.address=:80"
  #    - "--entrypoints.websecure.address=:443"
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - "/var/run/docker.sock:/var/run/docker.sock:ro"

  vault:
    image: "kerberos/vault:1.0.1398121865"
    restart: always
    container_name: "kerberos-vault"
    hostname: "kerberos-vault"
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - "./vault:/vault"
    environment:
      - GIN_MODE=release
      - KERBEROS_LOGIN_USERNAME=root
      - KERBEROS_LOGIN_PASSWORD=pass

      # This is the mongodb database where data will be stored, you might use a different name if you want.
      - MONGODB_DATABASE_STORAGE=KerberosStorage

      # MongoDB URI (for example for a SaaS service like MongoDB Atlas)
      # If uri is set, the below properties are not used (host, adminDatabase, username, password)
      #- MONGODB_URI="mongodb+srv://xx:xx@kerberos-hub.xxx.mongodb.net/?retryWrites=true&w=majority&appName=xxx"

      # If you do not wish to use the URI, you can specify the individual values.
      - MONGODB_HOST=mongo
      - MONGODB_DATABASE_CREDENTIALS=admin
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=pass

      # MQTT broker to be used for on-demand forwarding.
      - MQTTURI=
      - MQTT_USERNAME=
      - MQTT_PASSWORD=

      # If you have a chained vault setup, enable this.
      - CONTINUOUS_FORWARDING=false
    #labels:
    #  - 'traefik.enable=true'
    #  - 'traefik.http.routers.kerberos-vault.rule=Host(`kerberos-vault.domain.tld`)'
    #  - 'traefik.http.routers.kerberos-vault.entrypoints=web'
    #  - 'traefik.http.routers.kerberos-vault.tls=false'
    #  - 'traefik.http.routers.kerberos-vault.tls.certresolver=leresolver'
    #  - "traefik.http.routers.kerberos-vault.service=kerberos_vault"
    #  - 'traefik.http.services.kerberos_vault.loadbalancer.server.port=80'

  mongo:
    image: "mongo:4.4.16" # or mongo:5.x, mongo:6.x or later
    container_name: "mongo"
    hostname: "mongo"
    ports:
      - 27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
```

2. Attempt to delete it.

Output of the following command on your server:

```
uname -a && lsb_release -a && free -h
```

Linux [...] 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:Ubuntu
Description:Ubuntu 24.04.1 LTS
Release:24.04
Codename:noble
               total        used        free      shared  buff/cache   available
Mem:           1.8Gi       1.4Gi       255Mi        20Mi       350Mi       429Mi
Swap:             0B          0B          0B
