### ISSUE TITLE
Add override in captain definition?

### ISSUE THREAD

**Issue by therepo90** [caprover/caprover#2208]
Is it possible to add service ovveride via docker captain definition? I dont want to do it manually as its gone on restart(?).
Same thing goes for nginx override. 
```
TaskTemplate:
  Resources:
    Limits:
      MemoryBytes:  104857600
      NanoCPUs: 2000000000
```
