### ISSUE TITLE
Github Action Fails, NPM Repo Missing

### ISSUE THREAD

**Issue by lfender6445** [caprover/caprover#2219]
My github action started failing, resulting from a missing package:

https://www.npmjs.com/package/caprover 

```yml
- name: Deploy Image to CapRrover
  id: deploy
  uses: caprover/deploy-from-github@v1.1.2
  if: steps.semantic.outputs.new_release_published
  with:
    server: "${{ secrets.CAPROVER_SERVER }}"
    app: "${{ secrets.APP_NAME }}"
    token: "${{ secrets.APP_TOKEN }}"
    image: ${{ steps.set_image_tag.outputs.image_tag }}
```

https://registry.npmjs.org/caprover is suddenly showing a 404 for this package. Appears to have started in the last hour

```
  #7 1.483 npm ERR! 404 Not Found - GET https://registry.npmjs.org/caprover - Not found
  #7 1.483 npm ERR! 404 
  #7 1.483 npm ERR! 404  'caprover@*' is not in this registry.
  #7 1.483 npm ERR! 404 
  #7 1.483 npm ERR! 404 Note that you can also install from a
  #7 1.484 npm ERR! 404 tarball, folder, http url, or git url.
  #7 1.485 
  #7 1.485 npm ERR! A complete log of this run can be found in:
  #7 1.485 npm ERR!     /root/.npm/_logs/2024-12-08T18_18_29_059Z-debug-0.log
  #7 ERROR: process "/bin/sh -c apk add --no-cache git  && npm i -g caprover  && npm cache clean --force" did not complete successfully: exit code: 1
```
## Shell Example

```
> npm install -g caprover
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/caprover - Not found
npm ERR! 404
npm ERR! 404  'caprover@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/lfender-mba/.npm/_logs/2024-12-08T18_32_38_150Z-debug-0.log
```
## Screenshots
![image](https://github.com/user-attachments/assets/656c6671-b2f7-44e8-a3b0-b02b1c8e4629)

[Web archive shows this used to exist](https://web.archive.org/web/20230305111100/https://www.npmjs.com/package/caprover): 

![image](https://github.com/user-attachments/assets/fd3f9b73-23f7-43db-8974-48732ffa3a7d)

Here is what the page looks like now: 

![image](https://github.com/user-attachments/assets/27b53e76-a379-4edc-82d4-2978be551e03)
