### ISSUE TITLE
[Question] how to mount host directory inside caprover app?

### ISSUE THREAD

**Issue by pcace** [caprover/caprover#2262]
Hi there, i want to use an external directory (/mnt/data/database on the host system) to be used in an app as a persistant directory at /database in the container. 

i have tried to add a service override like this: 

```
TaskTemplate:
    Mounts:
      - Type: bind
        Source: /mnt/data/geodata/pg_17
        Target: /db
```
without success. what is the trick here to use this folder inside the container?

i also tried additionally to add a persistant folder on /db but this then just creates a new volume under /var/lib/docker/volumes (on the host) as expected. 

whats the way to go here?
