### ISSUE TITLE
How to use an App to have NGiNG handle an app already running on a specific port

### ISSUE THREAD

**Issue by marcopeg** [caprover/caprover#369]
Use case: I have a fairly complicated app with multiple containers running under a single NGiNX proxy. Such app is orchestrated with `docker-compose` and when running, she exposes only a specific port - say 8080.

Is there a way to configure a Caprover App so to leverage the awesome NGiNX/Letsencrypt automations and forward traffic to that specific port?

Thanks,
Marco

**Comment by githubsaturn** [comment]
Yes - if I understand your question correctly, you'd like to bind to a non-80 port of a particular app. You can change your container HTTP port to 8080 or anything specific to that container.

![screenshot from 2019-02-10 09-36-37](https://user-images.githubusercontent.com/10582082/52537084-65fba880-2d17-11e9-899b-dff02b0d2ce1.png)

**Comment by marcopeg** [comment]
Hi, my use case is a bit different:

I run a docker-compose stack on the same server where I run cap-rover.
That stack exposes itself on one (or more) ports in the host.

CapRover can't really communicate directly with those services via docker-dns because they run on different networks (swarm / compose).

So CapRover's App NGiNX should redirect traffic straight into the host's loopback network, instead of trying to go to the swarm's internal dns.

I got that to work by editing the NGiNX config file and fixing `$upstream = {HOST_PUBLIC_IP}:{COMPOSE_PROJECT_PORT}` and it work just fine.

The problem now is that that port will be open to the public, and I'm trying to fix that with some firewall rules. This solution might be improved if CapRover could provide an NGiNX variable with the internal IP that from inside a docker container points to the host machine.

NOTE: all of this is just to be able to enjoy CapRover's amazing DNS / SSL management without the hassle of migrating a docker-compose stack into a list of Apps that mut be manually defined. It's definelty a good to have, but not a critical feature.

Anyway, I would like to hear some ideas on the subject. In my company we do have a couple of machines running docker-compose stacks, and it would be nice to install CapRover on them :-)

**Comment by githubsaturn** [comment]
Okay, I _think_ I got it. 

So all you need to do is to make sure that your "web" service in your docker compose is accessible from the nginx container. You can do this by adding `captain-overlay-network` to that service. For example, something like this:

```
version: "3.3"

services:
  wordpress:
    image: wordpress
    networks:
      - captain-overlay-network
      - any-other-network
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

  mysql:
    image: mysql
    volumes:
       - db-data:/var/lib/mysql/data
    networks:
       - overlay
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr

volumes:
  db-data:

networks:
  any-other-network:
```

Then you just use whatever service name you chose for your web app:
```
set $upstream http://your-wordpress-service-name:your-internal-port-not-mapped;
```
