### ISSUE TITLE
How install laravel with custom nginx confgiuration

### ISSUE THREAD

**Issue by hamza-younas94** [caprover/caprover#380]
currently my project using docker-composer i have install caprover so i cant use docker-compose but with caprover how i use my custom configuration in it ?

**Comment by githubsaturn** [comment]
What is your "custom nginx configuration"? You can edit nginx config in the dashboard.

Can you provide more details? In fact, share you docker-compose file here so I can understand what your requirements are.

**Comment by hamza-younas94** [comment]
Thank you for your quick response here my docker-compose content which i want achieve same thing in captainduckduck/caprover

```
version: "3.5"
services:
  my_webserver:
    image: nginx
    container_name: my_webserver
    restart: always
    volumes:
      - ./laravel-app:/var/www
      - ./configuration/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
     # - 443:443
    networks:
      - my-network
    links:
      - my_laravel  
  my_laravel:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile     
    container_name: my_laravel
    volumes:
      - ./laravel-app:/var/www
      - ./configuration/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - my_postgres
    networks:
      - my-network       
  my_postgres:
    image: postgres
    container_name: my_postgres  
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql/data
    networks:
      - my-network
  my_adminer:
    image: adminer
    container_name: my_adminer  
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
```

Dockerfile
```
FROM php:7.2-fpm

# Copy composer.lock and composer.json
COPY composer.lock composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    mysql-client \
    libpng-dev \
    libpq-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql pdo_pgsql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Change current user to www
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
```



nginx conf
```
server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #this name should be container name
        fastcgi_pass hugo_laravel:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}
```

**Comment by hamza-younas94** [comment]
i hope your reply will solve my complete confusion may be you help me out to use my complete docker-compose.yml

**Comment by githubsaturn** [comment]
I assume you were able to create a Postgres and Adminer containers successfully. Read on:

- You need to create an app for your Lavarel app. Do that by going to the dashboard and create a new app with "Persistent Data". Then go to app's settings (config tab) and add two persistent directories:

You have this in your compose:
``
    volumes:
      - ./laravel-app:/var/www
      - ./configuration/php/local.ini:/usr/local/etc/php/conf.d/local.ini
```

Which means SPECIFIC PATH ON HOST:

```
Host directory:
./laravel-app (use absolute path)
Container directory:
/var/www
```

Keep Dockerfile as is.

- You don't need to create an nginx container as it's already included by default. Just go to your app's settings page on the dashboard and make edits there. Open web dashboard > Apps > Lavarel App > HTTP Settings > Edit Nginx Config.

**Comment by githubsaturn** [comment]
Last but not least, this is advanced process. If you're unfamiliar with how Docker works, it will be very difficult for you to do this conversion.

An easier approach for your, is to keep your working stack as is and install CapRover alongside:
1) Edit your compose file to make sure nginx is running on the same network as CapRover and does not block port 80
```
  my_webserver:
    image: nginx
    container_name: my_webserver
    restart: always
    volumes:
      - ./laravel-app:/var/www
      - ./configuration/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 5454:80
    networks:
      - my-network
      - captain-overlay-network
    links:
      - my_laravel  
```

Notice the two changes: `captain-overlay-network` and `5454:80`


2) Refresh your Docker compose stack. `docker-compose up -d`

3) Install CapRover

4) Create an empty app on CapRover.

5) Go to App's Settings > HTTP Settings and Edit Nginx Config and change this line:
```
set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;
```

To 

```
set $upstream http://123.123.123.123:5454;
```

where 123.123.123.123 is the public IP of your server, and 5454 is the new nginx port
