### ISSUE TITLE
Deploy local image

### ISSUE THREAD

**Issue by tonxxd** [caprover/caprover#633]
Is it possible to deploy a local built image without having to upload it first to docker hub or other container registries?

Thanks

**Comment by githubsaturn** [comment]
There is no built-in shortcut for it, but you can definitely create a simple script that does that.

create a file called `deployimage.sh` something like this

```
#!/bin/bash
source_image_name=$1

# replace repository.com with a remote registry
# if you need a private registry, you can use gitlab which is free

docker tag $source_image_name repository.com/username/$source_image_name
caprover deploy --imageName repository.com/username/source_image_name
```

Then run `deployimage.sh my_local_image`

**Comment by tonxxd** [comment]
Thanks! So I still need a remote registry, right? Also, is there a way to inform caprover of a new build from, for example, Gitlab CI/CD or caprvoer will try to build the image itself every time instead of just pulling? I am saying this because it runs out of memory (4gb ram) during npm install so I am looking for deployment alternatives.

**Comment by githubsaturn** [comment]
> So I still need a remote registry, right? 

Yes, I personally use gitlab as they offer free private registry.


With regards to CI/CD usage, yes, this is definitely possible and in fact I use this flow in my own applications. I push my code to gitlab, then it gets built on Gitlab server and gets pushed to gitlab registry, then it runs `caprover deploy`

The content of `.gitlab-ci.yml` is something like this:
```
build-master:
  image: docker:19.03.1
  stage: build
  services:
    - docker:19.03.1-dind
  before_script:
    - export DOCKER_REGISTRY_USER=$CI_REGISTRY_USER
    - export DOCKER_REGISTRY_PASSWORD=$CI_REGISTRY_PASSWORD
    - export DOCKER_REGISTRY_URL=$CI_REGISTRY
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY_URL

  script:
    - echo "Building..." # MAKE SURE NO SPACE ON EITHER SIDE OF = IN THE FOLLOWING LINE
    - export CONTAINER_FULL_IMAGE_NAME_WITHOUT_TAG=$CI_REGISTRY_IMAGE
    - export CONTAINER_FULL_IMAGE_NAME_WITH_TAG=$CONTAINER_FULL_IMAGE_NAME_WITHOUT_TAG:$CI_COMMIT_SHA
    - docker build -f ./Dockerfile --pull -t built-image-name .
    - docker tag built-image-name "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
    - docker push "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
    - echo $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
    - #### INSTALL node and caprover
    - caprover deploy --imageName registry.gitlab.com/username/reponame:tag -u URLHERE... -p PASSWORD -a APPNAME
  only:
    - master
```
