### ISSUE TITLE
I need order of execution of apps. Or dependent apps feature

### ISSUE THREAD

**Issue by alexk345** [caprover/caprover#793]
I rebooted by lightsail instance... took forver for caprover to come online. Should be some nice way to start caprover page  and show when its ready to login. Show login page but disable until caprover is ready.

Also my mongodb load slower or something my server app dont connect it . I had to rebuild code to get it connected. 

There need to be hook  between apps. When one start listening other can start.  I know docker compose has that.  But i want it caprover so when i reboot my instance i dont need to touch anything again.

Atpresent my data in mongodb dont show and dont connect unless i redeploy my server manually

My local docker-compose.yaml
```
`version: '2'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    stdin_open: true 
    tty: true  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    restart: on-failure
    volumes:
      - ./data/db:/data/db
  ui:
    build: ./ui
    volumes:
      - ./ui:/usr/src/app/ui
      - /usr/src/app/ui/node_modules
    ports:
      - '80:80'
    depends_on:
      - api
    stdin_open: true 
    tty: true
  api:
    build: ./api
    volumes:
      - ./ui:/usr/src/app/api
      - /usr/src/app/api/node_modules
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    stdin_open: true 
    tty: true  

    command: bash -c "/usr/src/app/wait-for-it.sh --timeout=0 mongo:27017 && npm run dev"
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30`
```
it had wait ...

**Caprover can listen for db port before start other dependent app.**
