### ISSUE TITLE
Captain definition file unable to build remote dockerfile

### ISSUE THREAD

**Issue by radex02** [caprover/caprover#845]
What is the problem?

If applicable, content of `captain-definition` file:

```
captainVersion: 4
volumes:
  $$cap_appname-data
services:
  $$cap_appname:
    build: 'https://github.com/getgrav/docker-grav.git'
    environment:
       - GRAV_VERSION: '$$cap_version'
    volumes:
      - $$cap_appname-data:/var/www/html
    caproverExtra:
            containerHttpPort: '80'
caproverOneClickApp:
    variables:
        - id: '$$cap_version'
          label: Grav Version
          defaultValue: '1.6.27'
          description: Check out their release page for the valid tags https://github.com/getgrav/grav/tags
          validRegex: "/^.+$/"
    instructions:
        start: |-
            Modern, Crazy Fast, Ridiculously Easy and Amazingly Powerful Flat-File CMS.
            More details: https://getgrav.org/
        end: |-
            Grav has been successfully deployed!
    displayName: Grav
    isOfficial: true
    description:  Modern, Crazy Fast, Ridiculously Easy and Amazingly Powerful Flat-File CMS.
    documentation: See https://getgrav.org/

```

Steps to reproduce the problem:

Simply use the definition above on the template app

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu 18

- RAM?
64gb
