### ISSUE TITLE
Useless error messages when testing one-click configurations

### ISSUE THREAD

**Issue by NeoTheThird** [caprover/caprover#864]
When testing faulty one-click configs, the error messages are often useless.

The following config will yield this error (due to the port mapping on 80):

```yml
captainVersion: 4
services:
    $$cap_appname:
        image: alpine
        ports:
            - "80:1337"
caproverOneClickApp:
    instructions:
        start: |-
            This won't work and you won't know why
        end: |-
            See, what'd i tell ya
    displayName: Gah!
    isOfficial: true
    description: This'll error out
    documentation: https://nope
```

![image](https://user-images.githubusercontent.com/12068939/96385196-99503500-1192-11eb-85d3-f8cf33100163.png)

If you put in a really wonky config (such as the one below, note the absence of the `caproverOneClickApp` section), you'll just get a brief "Something bad happened" popup and then nothing:

```
captainVersion: 4
services:
```

Caprover could do some additional validation on the entered yml/json and display more useful error messages.
