### ISSUE TITLE
[Deployment Issue] Mailcow sogo reverse proxy

### ISSUE THREAD

**Issue by PortStone** [caprover/caprover#948]
What is the problem?
If I click login on SoGo it will redirect me to the upstream url

Steps to reproduce the problem:
Install mailcow and edit mailcow.conf with 8080 as port and 127.0.0.1 as ip
Use the following override (docker-compose.override.yml): 
```
version: '2.1'
services:
  nginx-mailcow:
    container_name: nginx-mailcow 
    expose:
      - "8080"
    networks:
      captain-overlay-network:
networks:
  captain-overlay-network:
    external: true
```

Install Nginx reverse proxy with the one click feature.

Set container Port to 80 and upstream URL to http://nginx-mailcow:8080 
It works as expected but if you go to SoGo and click login it will redirect you to http://nginx-mailcow:8080.
